Repository cafejojo/schaapi, pull requests merged in 2018-06, with the labels that each got.

#189 Add JUnit test runner to README.md
  README.md
Labels: documentation

#190 Add SPAM stage implementation to README
  README.md
Labels: documentation

#193 Make All Tests Internal Objects
  modules/mining-pipeline/directory-project-miner/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/miner/directory/ProjectMinerTest.kt
  modules/mining-pipeline/github-project-miner/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/miner/github/GithubProjectDownloaderTest.kt
  modules/mining-pipeline/github-project-miner/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/miner/github/TestProject.kt
  modules/mining-pipeline/java-jar-project-compiler/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/projectcompiler/javajar/ProjectCompilerTest.kt
  modules/mining-pipeline/java-maven-project-compiler/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/projectcompiler/javamaven/MavenInstallerTest.kt
  modules/mining-pipeline/java-maven-project-compiler/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/projectcompiler/javamaven/ProjectCompilerTest.kt
  modules/mining-pipeline/jimple-evosuite-test-generator/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/testgenerator/jimpleevosuite/ClassGeneratorTest.kt
  modules/mining-pipeline/jimple-evosuite-test-generator/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/testgenerator/jimpleevosuite/ClassWriterTest.kt
  modules/mining-pipeline/jimple-evosuite-test-generator/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/testgenerator/jimpleevosuite/EvoSuiteRunnerTest.kt
  modules/mining-pipeline/jimple-library-usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/DotGraphRendererTest.kt
  modules/mining-pipeline/jimple-library-usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/IntegrationTest.kt
  modules/mining-pipeline/jimple-library-usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/filters/StatementFilterTest.kt
  modules/mining-pipeline/jimple-library-usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/filters/ValueFilterTest.kt
  modules/mining-pipeline/jimple-pattern-filter/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/patternfilter/jimple/IncompleteInitPatternFilterRuleTest.kt
  modules/mining-pipeline/jimple-pattern-filter/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/patternfilter/jimple/LengthPatternFilterRuleTest.kt
  modules/mining-pipeline/prefix-span-pattern-detector/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/patterndetector/prefixspan/PrefixSpanTest.kt
  modules/mining-pipeline/prefix-span-pattern-detector/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/patterndetector/prefixspan/TestNodeComparator.kt
  modules/mining-pipeline/spam-pattern-detector/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/patterndetector/spam/SpamTest.kt
  modules/mining-pipeline/spam-pattern-detector/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/patterndetector/spam/TestNodeComparator.kt
  modules/models/jimple-library-usage-graph/src/test/kotlin/org/cafejojo/schaapi/models/libraryusagegraph/jimple/GeneralizedNodeComparatorStructureTest.kt
  modules/models/jimple-library-usage-graph/src/test/kotlin/org/cafejojo/schaapi/models/libraryusagegraph/jimple/GeneralizedNodeComparatorValueTest.kt
  modules/models/jimple-library-usage-graph/src/test/kotlin/org/cafejojo/schaapi/models/libraryusagegraph/jimple/JimpleNodeTest.kt
  modules/models/jimple-library-usage-graph/src/test/kotlin/org/cafejojo/schaapi/models/libraryusagegraph/jimple/SimpleSoot.kt
  modules/models/jimple-library-usage-graph/src/test/kotlin/org/cafejojo/schaapi/models/libraryusagegraph/jimple/SootMockFactory.kt
  modules/validation-pipeline/junit-test-runner/src/test/kotlin/org/cafejojo/schaapi/validationpipeline/testrunner/junit/TestRunnerTest.kt
Labels: code quality

#191 Move `Pipeline` to `miningpipeline.MiningPipeline`
  modules/application/src/main/kotlin/org/cafejojo/schaapi/CommandLineInterface.kt
  modules/mining-pipeline/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/MiningPipeline.kt
Labels: code quality

#192 Skip AppVeyor builds modifying only the README
  README.md
  appveyor.yml
Labels: tooling

#181 Add CCSpan pattern detector
  modules/mining-pipeline/ccspan-pattern-detector/build.gradle
  modules/mining-pipeline/ccspan-pattern-detector/gradle.properties
  modules/mining-pipeline/ccspan-pattern-detector/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/patterndetector/ccspan/CCSpan.kt
  modules/mining-pipeline/ccspan-pattern-detector/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/patterndetector/ccspan/PatternDetector.kt
  modules/mining-pipeline/ccspan-pattern-detector/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/patterndetector/ccspan/CCSpanTest.kt
  modules/mining-pipeline/ccspan-pattern-detector/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/patterndetector/ccspan/TestNodeComparator.kt
  settings.gradle
Labels: enhancement

#195 Add CCSpan to README.md
  README.md
Labels: documentation

#196 Gradle cleanup
  modules/models/build.gradle
  modules/web/build.gradle
Labels: tooling

#160 Add GitHub app bearer token generation
  modules/github-test-reporter/build.gradle
  modules/github-test-reporter/gradle.properties
  modules/github-test-reporter/src/main/kotlin/org/cafejojo/schaapi/githubtestreporter/AppKeyGenerator.kt
  modules/github-test-reporter/src/main/kotlin/org/cafejojo/schaapi/githubtestreporter/Properties.kt
  modules/github-test-reporter/src/test/kotlin/org/cafejojo/schaapi/githubtestreporter/AppKeyGeneratorTest.kt
  modules/github-test-reporter/src/test/resources/pkcs8_key
  settings.gradle
Labels: enhancement

#199 Fix Detekt rule violations
  detekt.yml
  modules/github-test-reporter/src/main/kotlin/org/cafejojo/schaapi/githubtestreporter/AppKeyGenerator.kt
  modules/mining-pipeline/prefix-span-pattern-detector/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/patterndetector/prefixspan/PrefixSpan.kt
  modules/mining-pipeline/spam-pattern-detector/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/patterndetector/spam/Spam.kt
  modules/models/src/main/kotlin/org/cafejojo/schaapi/models/CustomEqualsCollections.kt
  modules/models/src/test/kotlin/org/cafejojo/schaapi/models/CustomEqualsCollectionsTest.kt
  modules/validation-pipeline/junit-test-runner/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/testrunner/junit/TestRunner.kt
Labels: code quality

#200 Fix key path on Windows in AppKeyGeneratorTest
  modules/github-test-reporter/src/main/kotlin/org/cafejojo/schaapi/githubtestreporter/AppKeyGenerator.kt
  modules/github-test-reporter/src/test/kotlin/org/cafejojo/schaapi/githubtestreporter/AppKeyGeneratorTest.kt
Labels: bug

#201 Remove unused imports in AppKeyGenerator and test
  modules/github-test-reporter/src/main/kotlin/org/cafejojo/schaapi/githubtestreporter/AppKeyGenerator.kt
  modules/github-test-reporter/src/test/kotlin/org/cafejojo/schaapi/githubtestreporter/AppKeyGeneratorTest.kt
Labels: code quality, critical

#202 Ignore Gradle wrapper jar and properties
  .gitignore
Labels: bug, tooling

#203 Improve readability of `pathContainsSequence`
  modules/models/src/main/kotlin/org/cafejojo/schaapi/models/PathUtil.kt
Labels: code quality

#204 Speed up frequent singleton detection
  modules/mining-pipeline/ccspan-pattern-detector/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/patterndetector/ccspan/CCSpan.kt
  modules/mining-pipeline/prefix-span-pattern-detector/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/patterndetector/prefixspan/PrefixSpan.kt
  modules/mining-pipeline/prefix-span-pattern-detector/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/patterndetector/prefixspan/PrefixSpanTest.kt
  modules/mining-pipeline/spam-pattern-detector/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/patterndetector/spam/Spam.kt
  modules/models/src/main/kotlin/org/cafejojo/schaapi/models/PathUtil.kt
Labels: enhancement

#205 Custom equals list
  modules/models/src/main/kotlin/org/cafejojo/schaapi/models/CustomEqualsCollections.kt
  modules/models/src/test/kotlin/org/cafejojo/schaapi/models/CustomEqualsCollectionsTest.kt
Labels: enhancement

#207 Parallelize streaming statements in CCSpan
  modules/mining-pipeline/ccspan-pattern-detector/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/patterndetector/ccspan/CCSpan.kt
  modules/models/src/main/kotlin/org/cafejojo/schaapi/models/PathUtil.kt
Labels: enhancement

#209 Logger config
  modules/application/src/main/resources/logback.xml
Labels: code quality

#210 Cache the supports calculated during CCSpan
  modules/mining-pipeline/ccspan-pattern-detector/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/patterndetector/ccspan/CCSpan.kt
Labels: enhancement

#208 Replace missing targets with returns
  modules/mining-pipeline/jimple-evosuite-test-generator/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/testgenerator/jimpleevosuite/ClassGenerator.kt
  modules/mining-pipeline/jimple-evosuite-test-generator/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/testgenerator/jimpleevosuite/ClassGeneratorTest.kt
Labels: bug

#211 Add log messages to PatternFilterRules
  modules/mining-pipeline/jimple-pattern-filter/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/patternfilter/jimple/IncompleteInitPatternFilterRule.kt
  modules/mining-pipeline/jimple-pattern-filter/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/patternfilter/jimple/LengthPatternFilterRule.kt
Labels: enhancement

#212 Filter recursive goto statements
  modules/mining-pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/LibraryUsageGraphGenerator.kt
  modules/mining-pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/filters/RecursiveGotoFilter.kt
  modules/mining-pipeline/jimple-library-usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/filters/RecursiveGotoFilterTest.kt
Labels: enhancement

#213 Add copy method to `Node`s
  modules/models/jimple-library-usage-graph/src/main/kotlin/org/cafejojo/schaapi/models/libraryusagegraph/jimple/JimpleNode.kt
  modules/models/jimple-library-usage-graph/src/test/kotlin/org/cafejojo/schaapi/models/libraryusagegraph/jimple/JimpleNodeTest.kt
  modules/models/src/main/kotlin/org/cafejojo/schaapi/models/Node.kt
Labels: enhancement

#215 Stop unrolling loops in the `PathEnumerator`
  modules/models/src/main/kotlin/org/cafejojo/schaapi/models/PathEnumerator.kt
  modules/models/src/test/kotlin/org/cafejojo/schaapi/models/PathEnumeratorTest.kt
Labels: bug

#197 Add GitHub check reporter
  detekt.yml
  modules/github-test-reporter/build.gradle
  modules/github-test-reporter/gradle.properties
  modules/github-test-reporter/src/main/kotlin/org/cafejojo/schaapi/githubtestreporter/AppKeyGenerator.kt
  modules/github-test-reporter/src/main/kotlin/org/cafejojo/schaapi/githubtestreporter/CheckReporter.kt
  modules/github-test-reporter/src/main/kotlin/org/cafejojo/schaapi/githubtestreporter/CheckSuiteEvent.kt
  modules/github-test-reporter/src/main/kotlin/org/cafejojo/schaapi/githubtestreporter/CustomHttpClient.kt
  modules/github-test-reporter/src/main/kotlin/org/cafejojo/schaapi/githubtestreporter/FuelConfiguration.kt
  modules/github-test-reporter/src/main/kotlin/org/cafejojo/schaapi/githubtestreporter/GitHubApi.kt
  modules/github-test-reporter/src/main/kotlin/org/cafejojo/schaapi/githubtestreporter/JsonObjectBuilder.kt
  modules/github-test-reporter/src/main/kotlin/org/cafejojo/schaapi/githubtestreporter/WebHookReceiver.kt
  modules/github-test-reporter/src/test/kotlin/org/cafejojo/schaapi/githubtestreporter/AppKeyGeneratorTest.kt
  modules/github-test-reporter/src/test/kotlin/org/cafejojo/schaapi/githubtestreporter/CheckReporterTest.kt
  modules/github-test-reporter/src/test/kotlin/org/cafejojo/schaapi/githubtestreporter/Helpers.kt
  modules/github-test-reporter/src/test/kotlin/org/cafejojo/schaapi/githubtestreporter/IntegrationTest.kt
  modules/github-test-reporter/src/test/kotlin/org/cafejojo/schaapi/githubtestreporter/WebHookReceiverTest.kt
  modules/github-test-reporter/src/test/resources/fixtures/github/check_suite_webhook.resp
  modules/github-test-reporter/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
Labels: enhancement

#198 GitHub Mining Integration
  README.md
  modules/application/build.gradle
  modules/application/src/main/kotlin/org/cafejojo/schaapi/CommandLineInterface.kt
  modules/application/src/module-integration-test/kotlin/org/cafejojo/schaapi/SchaapiSmokeTest.kt
  modules/mining-pipeline/github-project-miner/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/miner/github/GitHubProjectDownloader.kt
  modules/mining-pipeline/github-project-miner/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/miner/github/ProjectMiner.kt
  modules/mining-pipeline/github-project-miner/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/miner/github/SearchOptions.kt
  modules/mining-pipeline/github-project-miner/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/miner/github/GithubProjectDownloaderTest.kt
  modules/mining-pipeline/java-maven-project-compiler/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/projectcompiler/javamaven/ProjectCompiler.kt
  modules/mining-pipeline/prefix-span-pattern-detector/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/patterndetector/prefixspan/PatternDetector.kt
  modules/mining-pipeline/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/MiningPipeline.kt
  modules/mining-pipeline/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/ProjectCompiler.kt
  modules/models/java-project/src/main/kotlin/org/cafejojo/schaapi/models/project/JavaMavenProject.kt
Labels: bug, code quality, enhancement

#217 Filter instance and array references in ClassGenerator
  modules/mining-pipeline/jimple-evosuite-test-generator/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/testgenerator/jimpleevosuite/ClassGenerator.kt
  modules/mining-pipeline/jimple-evosuite-test-generator/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/testgenerator/jimpleevosuite/ClassGeneratorTest.kt
Labels: bug

#219 Fix duplicate locals
  modules/mining-pipeline/jimple-evosuite-test-generator/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/testgenerator/jimpleevosuite/ClassGenerator.kt
  modules/mining-pipeline/jimple-evosuite-test-generator/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/testgenerator/jimpleevosuite/ClassGeneratorTest.kt
Labels: bug

#221 Filter more field refs
  modules/mining-pipeline/jimple-evosuite-test-generator/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/testgenerator/jimpleevosuite/ClassGenerator.kt
  modules/mining-pipeline/jimple-evosuite-test-generator/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/testgenerator/jimpleevosuite/ClassGeneratorTest.kt
Labels: bug

#220 Make copies of nodes in each sequence, while maintaining referential integrity
  modules/mining-pipeline/jimple-evosuite-test-generator/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/testgenerator/jimpleevosuite/ClassGenerator.kt
  modules/mining-pipeline/jimple-evosuite-test-generator/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/testgenerator/jimpleevosuite/ClassGeneratorTest.kt
Labels: enhancement

#225 Ignore classes in META-INF in JavaJarCompiler
  modules/mining-pipeline/java-jar-project-compiler/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/projectcompiler/javajar/ProjectCompiler.kt
  modules/mining-pipeline/java-jar-project-compiler/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/projectcompiler/javajar/ProjectCompilerTest.kt
  modules/mining-pipeline/java-jar-project-compiler/src/test/resources/schaapi.simple-project-in-meta-inf-1.0.0.jar
  modules/mining-pipeline/java-jar-project-compiler/src/test/resources/simple-project-in-meta-inf/pom.xml
  modules/mining-pipeline/java-jar-project-compiler/src/test/resources/simple-project-in-meta-inf/src/main/java/org/cafejojo/schaapi/test/MyClass.java
  modules/mining-pipeline/java-jar-project-compiler/src/test/resources/simple-project-in-meta-inf/src/main/resources/META-INF/Test.class
Labels: bug

#216 Multiple pipelines
  README.md
  modules/application/build.gradle
  modules/application/src/main/kotlin/org/cafejojo/schaapi/CommandLineInterface.kt
  modules/application/src/main/kotlin/org/cafejojo/schaapi/DirectoryMiningCommandLineInterface.kt
  modules/application/src/main/kotlin/org/cafejojo/schaapi/GitHubMiningCommandLineInterface.kt
  modules/application/src/main/kotlin/org/cafejojo/schaapi/MissingArgumentException.kt
  modules/application/src/module-integration-test/kotlin/org/cafejojo/schaapi/SchaapiSmokeTest.kt
  modules/mining-pipeline/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/MiningPipeline.kt
Labels: enhancement

#224 Add GitHub sorting options
  README.md
  modules/application/src/main/kotlin/org/cafejojo/schaapi/GitHubMiningCommandLineInterface.kt
  modules/mining-pipeline/github-project-miner/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/miner/github/SearchOptions.kt
Labels: enhancement

#228 Receive installation web hooks
  modules/validation-pipeline/github-test-reporter/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/githubtestreporter/CheckReporter.kt
  modules/validation-pipeline/github-test-reporter/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/githubtestreporter/GitHubApi.kt
  modules/validation-pipeline/github-test-reporter/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/githubtestreporter/Properties.kt
  modules/validation-pipeline/github-test-reporter/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/githubtestreporter/WebHookReceiver.kt
  modules/validation-pipeline/github-test-reporter/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/githubtestreporter/events/CheckSuiteEvent.kt
  modules/validation-pipeline/github-test-reporter/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/githubtestreporter/events/InstallationEvent.kt
  modules/validation-pipeline/github-test-reporter/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/githubtestreporter/events/Shared.kt
  modules/validation-pipeline/github-test-reporter/src/test/kotlin/org/cafejojo/schaapi/validationpipeline/githubtestreporter/AppKeyGeneratorTest.kt
  modules/validation-pipeline/github-test-reporter/src/test/kotlin/org/cafejojo/schaapi/validationpipeline/githubtestreporter/CheckReporterTest.kt
  modules/validation-pipeline/github-test-reporter/src/test/kotlin/org/cafejojo/schaapi/validationpipeline/githubtestreporter/IntegrationTest.kt
  modules/validation-pipeline/github-test-reporter/src/test/kotlin/org/cafejojo/schaapi/validationpipeline/githubtestreporter/WebHookReceiverTest.kt
  modules/validation-pipeline/github-test-reporter/src/test/resources/fixtures/github/installation_created_webhook.resp
  modules/validation-pipeline/github-test-reporter/src/test/resources/fixtures/github/installation_deleted_webhook.resp
  modules/validation-pipeline/github-test-reporter/src/test/resources/githubtestreporter.properties
  modules/web/src/main/kotlin/org/cafejojo/schaapi/web/WebApplication.kt
Labels: enhancement

#231 Fix jimple sequence duplication
  modules/mining-pipeline/jimple-evosuite-test-generator/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/testgenerator/jimpleevosuite/ClassGenerator.kt
  modules/mining-pipeline/jimple-evosuite-test-generator/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/testgenerator/jimpleevosuite/ClassGeneratorTest.kt
Labels: bug

#230 Properly delete zip files
  modules/mining-pipeline/github-project-miner/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/miner/github/GitHubProjectDownloader.kt
  modules/mining-pipeline/github-project-miner/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/miner/github/GithubProjectDownloaderTest.kt
Labels: bug

#236 Recursive definition fix
  modules/mining-pipeline/jimple-evosuite-test-generator/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/testgenerator/jimpleevosuite/ClassGenerator.kt
  modules/mining-pipeline/jimple-evosuite-test-generator/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/testgenerator/jimpleevosuite/ClassGeneratorTest.kt
Labels: bug

#233 Fix equivalence of `Local`s
  build.gradle
  modules/application/build.gradle
  modules/mining-pipeline/jimple-evosuite-test-generator/build.gradle
  modules/mining-pipeline/jimple-library-usage-graph-generator/build.gradle
  modules/mining-pipeline/jimple-pattern-filter/build.gradle
  modules/mining-pipeline/prefix-span-pattern-detector/build.gradle
  modules/models/jimple-library-usage-graph/build.gradle
  modules/models/jimple-library-usage-graph/src/main/kotlin/org/cafejojo/schaapi/models/libraryusagegraph/jimple/JimpleNode.kt
Labels: bug

#232 Add empty loop filter
  modules/application/src/main/kotlin/org/cafejojo/schaapi/DirectoryMiningCommandLineInterface.kt
  modules/application/src/main/kotlin/org/cafejojo/schaapi/GitHubMiningCommandLineInterface.kt
  modules/mining-pipeline/jimple-pattern-filter/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/patternfilter/jimple/EmptyLoopPatternFilterRule.kt
  modules/mining-pipeline/jimple-pattern-filter/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/patternfilter/jimple/EmptyLoopPatternFilterRuleTest.kt
Labels: enhancement

#239 Add JUnit test engine
  build.gradle
Labels: bug

#238 Speed up class name containment checks in Projects
  modules/mining-pipeline/java-jar-project-compiler/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/projectcompiler/javajar/ProjectCompiler.kt
  modules/mining-pipeline/java-maven-project-compiler/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/projectcompiler/javamaven/ProjectCompiler.kt
  modules/mining-pipeline/jimple-library-usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/Helpers.kt
  modules/mining-pipeline/jimple-library-usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/IntegrationTest.kt
  modules/models/java-project/src/main/kotlin/org/cafejojo/schaapi/models/project/JavaJarProject.kt
  modules/models/java-project/src/main/kotlin/org/cafejojo/schaapi/models/project/JavaMavenProject.kt
  modules/models/java-project/src/main/kotlin/org/cafejojo/schaapi/models/project/JavaProject.kt
Labels: enhancement

#237 Use default default default
  modules/application/src/main/kotlin/org/cafejojo/schaapi/CommandLineInterface.kt
  modules/application/src/main/kotlin/org/cafejojo/schaapi/DirectoryMiningCommandLineInterface.kt
  modules/application/src/main/kotlin/org/cafejojo/schaapi/GitHubMiningCommandLineInterface.kt
Labels: code quality

#241 Use brace syntax for logging where possible
  modules/mining-pipeline/github-project-miner/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/miner/github/GitHubProjectDownloader.kt
  modules/mining-pipeline/java-jar-project-compiler/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/projectcompiler/javajar/ProjectCompiler.kt
  modules/mining-pipeline/java-maven-project-compiler/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/projectcompiler/javamaven/ProjectCompiler.kt
Labels: code quality

#242 Fix project mining step name in README
  README.md
Labels: documentation

#245 Update Kotlin to 1.2.50
  gradle.properties
Labels: code quality

#246 Add validation events
  modules/validation-pipeline/ci-job/build.gradle
  modules/validation-pipeline/ci-job/gradle.properties
  modules/validation-pipeline/ci-job/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/cijob/CIJobInitiator.kt
  modules/validation-pipeline/github-test-reporter/build.gradle
  modules/validation-pipeline/github-test-reporter/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/githubtestreporter/WebHookReceiver.kt
  modules/validation-pipeline/github-test-reporter/src/test/kotlin/org/cafejojo/schaapi/validationpipeline/githubtestreporter/WebHookReceiverTest.kt
  modules/validation-pipeline/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/events/ValidationRequestReceivedEvent.kt
  modules/web/build.gradle
  modules/web/src/main/kotlin/org/cafejojo/schaapi/web/WebApplication.kt
  settings.gradle
Labels: enhancement

#243 Add project compiler step to README
  README.md
Labels: documentation

#244 Remove all compilation warnings
  modules/mining-pipeline/jimple-evosuite-test-generator/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/testgenerator/jimpleevosuite/ClassGeneratorTest.kt
  modules/mining-pipeline/prefix-span-pattern-detector/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/patterndetector/prefixspan/PrefixSpan.kt
  modules/mining-pipeline/spam-pattern-detector/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/patterndetector/spam/Spam.kt
  modules/models/src/main/kotlin/org/cafejojo/schaapi/models/PathEnumerator.kt
Labels: code quality

#240 Do not retain non-library usages on LHS
  modules/mining-pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/filters/StatementFilter.kt
  modules/mining-pipeline/jimple-library-usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/IntegrationTest.kt
  modules/mining-pipeline/jimple-library-usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/filters/StatementFilterTest.kt
Labels: bug

#248 Add CIJob with downloading and zip extraction
  modules/validation-pipeline/ci-job/build.gradle
  modules/validation-pipeline/ci-job/gradle.properties
  modules/validation-pipeline/ci-job/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/cijob/CIJob.kt
  modules/validation-pipeline/ci-job/src/test/kotlin/org/cafejojo/schaapi/validationpipeline/cijob/CIJobTest.kt
Labels: enhancement

#247 Soot alternative solution
  build.gradle
  modules/application/build.gradle
  modules/mining-pipeline/jimple-evosuite-test-generator/build.gradle
  modules/mining-pipeline/jimple-library-usage-graph-generator/build.gradle
  modules/mining-pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/LibraryUsageGraphGenerator.kt
  modules/mining-pipeline/jimple-pattern-filter/build.gradle
  modules/mining-pipeline/prefix-span-pattern-detector/build.gradle
  modules/models/jimple-library-usage-graph/build.gradle
  modules/models/jimple-library-usage-graph/src/main/kotlin/org/cafejojo/schaapi/models/libraryusagegraph/jimple/SootNameEquivalenceChanger.kt
  modules/models/jimple-library-usage-graph/src/test/kotlin/org/cafejojo/schaapi/models/libraryusagegraph/jimple/JimpleNodeTest.kt
  modules/models/jimple-library-usage-graph/src/test/kotlin/org/cafejojo/schaapi/models/libraryusagegraph/jimple/SootNameEquivalenceChanger Test.kt
Labels: code quality

#250 Refactor long methods into smaller helper methods
  modules/application/src/main/kotlin/org/cafejojo/schaapi/CommandLineInterface.kt
  modules/mining-pipeline/java-maven-project-compiler/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/projectcompiler/javamaven/ProjectCompiler.kt
  modules/mining-pipeline/jimple-evosuite-test-generator/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/testgenerator/jimpleevosuite/ClassGenerator.kt
  modules/mining-pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/LibraryUsageGraphGenerator.kt
  modules/validation-pipeline/github-test-reporter/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/githubtestreporter/WebHookReceiver.kt
Labels: code quality

#249 Consistently use `@Suppress`
  modules/mining-pipeline/jimple-library-usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/filters/RecursiveGotoFilterTest.kt
  modules/models/java-project/src/main/kotlin/org/cafejojo/schaapi/models/project/JavaJarProject.kt
  modules/models/java-project/src/main/kotlin/org/cafejojo/schaapi/models/project/JavaMavenProject.kt
  modules/models/jimple-library-usage-graph/src/main/kotlin/org/cafejojo/schaapi/models/libraryusagegraph/jimple/GeneralizedNodeComparator.kt
  modules/models/jimple-library-usage-graph/src/main/kotlin/org/cafejojo/schaapi/models/libraryusagegraph/jimple/JimpleValueVisitor.kt
  modules/models/jimple-library-usage-graph/src/test/kotlin/org/cafejojo/schaapi/models/libraryusagegraph/jimple/JimpleNodeTest.kt
  modules/models/jimple-library-usage-graph/src/test/kotlin/org/cafejojo/schaapi/models/libraryusagegraph/jimple/SimpleSoot.kt
  modules/models/src/main/kotlin/org/cafejojo/schaapi/models/CustomEqualsCollections.kt
  modules/models/src/test/kotlin/org/cafejojo/schaapi/models/CustomEqualsCollectionsTest.kt
Labels: code quality

#252 Rename PathUtil to NodeSequenceUtil
  modules/mining-pipeline/ccspan-pattern-detector/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/patterndetector/ccspan/CCSpan.kt
  modules/mining-pipeline/prefix-span-pattern-detector/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/patterndetector/prefixspan/PrefixSpan.kt
  modules/mining-pipeline/spam-pattern-detector/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/patterndetector/spam/Spam.kt
  modules/models/src/main/kotlin/org/cafejojo/schaapi/models/NodeSequenceUtil.kt
  modules/models/src/main/kotlin/org/cafejojo/schaapi/models/PathUtil.kt
  modules/models/src/test/kotlin/org/cafejojo/schaapi/models/NodeSequenceUtilTest.kt
  modules/models/src/test/kotlin/org/cafejojo/schaapi/models/PathUtilTest.kt
Labels: code quality

#251 Upgrade `JimpleValueVisitor` to support more `Value`s
  modules/models/jimple-library-usage-graph/src/main/kotlin/org/cafejojo/schaapi/models/libraryusagegraph/jimple/JimpleValueVisitor.kt
  modules/models/jimple-library-usage-graph/src/test/kotlin/org/cafejojo/schaapi/models/libraryusagegraph/jimple/JimpleValueVisitorTest.kt
Labels: enhancement

#254 Add support for some miscellaneous Value classes
  modules/models/jimple-library-usage-graph/src/main/kotlin/org/cafejojo/schaapi/models/libraryusagegraph/jimple/JimpleValueVisitor.kt
  modules/models/jimple-library-usage-graph/src/test/kotlin/org/cafejojo/schaapi/models/libraryusagegraph/jimple/JimpleValueVisitorTest.kt
Labels: enhancement

#257 Remove unnecessary debug output
  modules/validation-pipeline/github-test-reporter/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/githubtestreporter/WebHookReceiver.kt
Labels: code quality

#258 Pattern detector fix
  modules/mining-pipeline/ccspan-pattern-detector/build.gradle
  modules/mining-pipeline/ccspan-pattern-detector/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/patterndetector/ccspan/CCSpan.kt
  modules/mining-pipeline/ccspan-pattern-detector/src/module-integration-test/kotlin/org/cafejojo/schaapi/miningpipeline/patterndetector/ccspan/CCSpanIntegrationTest.kt
  modules/models/jimple-library-usage-graph/src/main/kotlin/org/cafejojo/schaapi/models/libraryusagegraph/jimple/GeneralizedNodeComparator.kt
  modules/models/src/main/kotlin/org/cafejojo/schaapi/models/NodeSequenceUtil.kt
Labels: bug, critical

#259 CI Job: Gracefully handle errors and make them user reportable
  modules/application/src/main/kotlin/org/cafejojo/schaapi/CommandLineInterface.kt
  modules/mining-pipeline/java-maven-project-compiler/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/projectcompiler/javamaven/MavenInstaller.kt
  modules/validation-pipeline/ci-job/build.gradle
  modules/validation-pipeline/ci-job/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/cijob/CIJob.kt
  modules/validation-pipeline/ci-job/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/cijob/CIJobInitiator.kt
  modules/validation-pipeline/ci-job/src/main/resources/junit-4.12.jar
  modules/validation-pipeline/ci-job/src/test/kotlin/org/cafejojo/schaapi/validationpipeline/cijob/CIJobTest.kt
  modules/validation-pipeline/ci-job/src/test/kotlin/org/cafejojo/schaapi/validationpipeline/cijob/IntegrationTest.kt
  modules/validation-pipeline/ci-job/src/test/resources/projects/cafejojo/dummy-simple-maven-library/failing-tests/FailingRegressionTest_ESTest.java
  modules/validation-pipeline/ci-job/src/test/resources/projects/cafejojo/dummy-simple-maven-library/tests-construction/RegressionTest.java
  modules/validation-pipeline/ci-job/src/test/resources/projects/cafejojo/dummy-simple-maven-library/tests/RegressionTest.class
  modules/validation-pipeline/ci-job/src/test/resources/projects/cafejojo/dummy-simple-maven-library/tests/RegressionTest_ESTest.java
  modules/validation-pipeline/github-test-reporter/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/githubtestreporter/WebHookReceiver.kt
  modules/validation-pipeline/github-test-reporter/src/test/kotlin/org/cafejojo/schaapi/validationpipeline/githubtestreporter/WebHookReceiverTest.kt
  modules/validation-pipeline/junit-test-runner/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/testrunner/junit/TestRunner.kt
  modules/validation-pipeline/junit-test-runner/src/test/kotlin/org/cafejojo/schaapi/validationpipeline/testrunner/junit/TestRunnerTest.kt
  modules/validation-pipeline/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/TestRunner.kt
  modules/validation-pipeline/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/events/CIJobCompletedEvent.kt
  modules/validation-pipeline/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/events/ValidationRequestReceivedEvent.kt
Labels: enhancement

#261 CI Job: Small fixes
  modules/validation-pipeline/ci-job/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/cijob/CIJob.kt
  modules/validation-pipeline/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/events/CIJobCompletedEvent.kt
Labels: enhancement

#262 Restructure GitHub test reporter
  modules/validation-pipeline/github-test-reporter/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/githubtestreporter/CheckReporter.kt
  modules/validation-pipeline/github-test-reporter/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/githubtestreporter/WebHookReceiver.kt
  modules/validation-pipeline/github-test-reporter/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/githubtestreporter/githubapi/CustomHttpClient.kt
  modules/validation-pipeline/github-test-reporter/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/githubtestreporter/githubapi/FuelConfiguration.kt
  modules/validation-pipeline/github-test-reporter/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/githubtestreporter/githubapi/GitHubApi.kt
  modules/validation-pipeline/github-test-reporter/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/githubtestreporter/githubapi/JsonObjectBuilder.kt
  modules/validation-pipeline/github-test-reporter/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/githubtestreporter/webhookevents/CheckSuiteEvent.kt
  modules/validation-pipeline/github-test-reporter/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/githubtestreporter/webhookevents/InstallationEvent.kt
  modules/validation-pipeline/github-test-reporter/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/githubtestreporter/webhookevents/Shared.kt
  modules/validation-pipeline/github-test-reporter/src/test/kotlin/org/cafejojo/schaapi/validationpipeline/githubtestreporter/CheckReporterTest.kt
  modules/validation-pipeline/github-test-reporter/src/test/kotlin/org/cafejojo/schaapi/validationpipeline/githubtestreporter/Helpers.kt
  modules/validation-pipeline/github-test-reporter/src/test/kotlin/org/cafejojo/schaapi/validationpipeline/githubtestreporter/IntegrationTest.kt
  modules/validation-pipeline/github-test-reporter/src/test/kotlin/org/cafejojo/schaapi/validationpipeline/githubtestreporter/WebHookReceiverTest.kt
Labels: code quality

#263 Collision rename
  modules/application/src/main/kotlin/org/cafejojo/schaapi/DirectoryMiningCommandLineInterface.kt
  modules/application/src/main/kotlin/org/cafejojo/schaapi/GitHubMiningCommandLineInterface.kt
  modules/mining-pipeline/ccspan-pattern-detector/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/patterndetector/ccspan/CCSpanPatternDetector.kt
  modules/mining-pipeline/ccspan-pattern-detector/src/module-integration-test/kotlin/org/cafejojo/schaapi/miningpipeline/patterndetector/ccspan/CCSpanIntegrationTest.kt
  modules/mining-pipeline/directory-project-miner/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/miner/directory/DirectoryProjectMiner.kt
  modules/mining-pipeline/directory-project-miner/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/miner/directory/DirectorySearchOptions.kt
  modules/mining-pipeline/directory-project-miner/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/miner/directory/DirectoryProjectMinerTest.kt
  modules/mining-pipeline/github-project-miner/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/miner/github/GitHubProjectMiner.kt
  modules/mining-pipeline/java-jar-project-compiler/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/projectcompiler/javajar/JavaJarProjectCompiler.kt
  modules/mining-pipeline/java-jar-project-compiler/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/projectcompiler/javajar/JavaJarProjectCompilerTest.kt
  modules/mining-pipeline/java-maven-project-compiler/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/projectcompiler/javamaven/JavaMavenProjectCompiler.kt
  modules/mining-pipeline/java-maven-project-compiler/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/projectcompiler/javamaven/JavaMavenProjectCompilerTest.kt
  modules/mining-pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/JimpleLibraryUsageGraphGenerator.kt
  modules/mining-pipeline/jimple-library-usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/IntegrationTest.kt
  modules/mining-pipeline/prefix-span-pattern-detector/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/patterndetector/prefixspan/PrefixSpanPatternDetector.kt
  modules/mining-pipeline/prefix-span-pattern-detector/src/module-integration-test/kotlin/org/cafejojo/schaapi/miningpipeline/patterndetector/prefixspan/CCSpanJimpleNodeIntegrationTest.kt
  modules/mining-pipeline/spam-pattern-detector/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/patterndetector/spam/SpamPatternDetector.kt
  modules/validation-pipeline/ci-job/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/cijob/CIJob.kt
Labels: code quality

#260 Retain `DefinitionStmt` if either uses library
  modules/mining-pipeline/jimple-evosuite-test-generator/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/testgenerator/jimpleevosuite/ClassGeneratorTest.kt
  modules/mining-pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/filters/StatementFilter.kt
  modules/mining-pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/filters/ValueFilter.kt
  modules/mining-pipeline/jimple-library-usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/IntegrationTest.kt
  modules/mining-pipeline/jimple-library-usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/filters/StatementFilterTest.kt
  modules/mining-pipeline/jimple-library-usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/filters/ValueFilterTest.kt
Labels: bug

#265 Correct capitalization of Maven in log message
  modules/mining-pipeline/github-project-miner/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/miner/github/SearchOptions.kt
Labels: code quality, critical

#269 Ensure that clone of custom `JimpleLocal` is custom `JimpleLocal`
  modules/models/jimple-library-usage-graph/src/main/kotlin/org/cafejojo/schaapi/models/libraryusagegraph/jimple/SootNameEquivalenceChanger.kt
Labels: bug

#271 Custom equals sub-list
  modules/mining-pipeline/ccspan-pattern-detector/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/patterndetector/ccspan/CCSpan.kt
  modules/models/src/main/kotlin/org/cafejojo/schaapi/models/CustomEqualsCollections.kt
  modules/models/src/test/kotlin/org/cafejojo/schaapi/models/CustomEqualsCollectionsTest.kt
Labels: bug

#268 Fire failed events after unsuccessful CI job runs
  modules/validation-pipeline/ci-job/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/cijob/CIJob.kt
  modules/validation-pipeline/ci-job/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/cijob/CIJobInitiator.kt
  modules/validation-pipeline/ci-job/src/test/kotlin/org/cafejojo/schaapi/validationpipeline/cijob/CIJobTest.kt
  modules/validation-pipeline/ci-job/src/test/kotlin/org/cafejojo/schaapi/validationpipeline/cijob/IntegrationTest.kt
  modules/validation-pipeline/github-test-reporter/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/githubtestreporter/Properties.kt
  modules/validation-pipeline/github-test-reporter/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/githubtestreporter/WebHookReceiver.kt
  modules/validation-pipeline/github-test-reporter/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/githubtestreporter/webhookevents/CheckSuiteEvent.kt
  modules/validation-pipeline/github-test-reporter/src/test/kotlin/org/cafejojo/schaapi/validationpipeline/githubtestreporter/WebHookReceiverTest.kt
  modules/validation-pipeline/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/CIJobException.kt
  modules/validation-pipeline/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/events/CIJobCompletedEvent.kt
  modules/validation-pipeline/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/events/CIJobFailedEvent.kt
  modules/validation-pipeline/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/events/CIJobSucceededEvent.kt
Labels: enhancement

#267 Remove copy-dependencies step in Maven compiler
  modules/application/src/module-integration-test/resources/user/a/pom.xml
  modules/application/src/module-integration-test/resources/user/a/src/main/java/org/cafejojo/schaapi/test/user/a/UserClass.java
  modules/mining-pipeline/java-maven-project-compiler/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/projectcompiler/javamaven/JavaMavenProjectCompiler.kt
  modules/mining-pipeline/java-maven-project-compiler/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/projectcompiler/javamaven/JavaMavenProjectCompilerTest.kt
Labels: enhancement

#274 Always initialize local variables in the ClassGenerator
  modules/mining-pipeline/jimple-evosuite-test-generator/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/testgenerator/jimpleevosuite/ClassGenerator.kt
  modules/mining-pipeline/jimple-evosuite-test-generator/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/testgenerator/jimpleevosuite/ClassGeneratorTest.kt
Labels: bug, enhancement

#278 Use range instead of creating a new list
  modules/mining-pipeline/ccspan-pattern-detector/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/patterndetector/ccspan/CCSpan.kt
Labels: code quality

#279 Set default log level to 'info'
  modules/application/src/main/resources/logback.xml
Labels: enhancement

#275 Jimple-aware enumerator
  modules/application/src/main/kotlin/org/cafejojo/schaapi/DirectoryMiningCommandLineInterface.kt
  modules/application/src/main/kotlin/org/cafejojo/schaapi/GitHubMiningCommandLineInterface.kt
  modules/mining-pipeline/ccspan-pattern-detector/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/patterndetector/ccspan/CCSpanPatternDetector.kt
  modules/mining-pipeline/ccspan-pattern-detector/src/module-integration-test/kotlin/org/cafejojo/schaapi/miningpipeline/patterndetector/ccspan/CCSpanIntegrationTest.kt
  modules/mining-pipeline/prefix-span-pattern-detector/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/patterndetector/prefixspan/PrefixSpanPatternDetector.kt
  modules/mining-pipeline/prefix-span-pattern-detector/src/module-integration-test/kotlin/org/cafejojo/schaapi/miningpipeline/patterndetector/prefixspan/CCSpanJimpleNodeIntegrationTest.kt
  modules/mining-pipeline/spam-pattern-detector/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/patterndetector/spam/SpamPatternDetector.kt
  modules/models/jimple-library-usage-graph/src/main/kotlin/org/cafejojo/schaapi/models/libraryusagegraph/jimple/JimplePathEnumerator.kt
  modules/models/jimple-library-usage-graph/src/test/kotlin/org/cafejojo/schaapi/models/libraryusagegraph/jimple/JimplePathEnumeratorTest.kt
  modules/models/src/main/kotlin/org/cafejojo/schaapi/models/PathEnumerator.kt
  modules/models/src/test/kotlin/org/cafejojo/schaapi/models/PathEnumeratorTest.kt
Labels: bug

#284 Remove unused pattern detectors and update README
  README.md
  modules/mining-pipeline/prefix-span-pattern-detector/build.gradle
  modules/mining-pipeline/prefix-span-pattern-detector/gradle.properties
  modules/mining-pipeline/prefix-span-pattern-detector/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/patterndetector/prefixspan/PrefixSpan.kt
  modules/mining-pipeline/prefix-span-pattern-detector/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/patterndetector/prefixspan/PrefixSpanPatternDetector.kt
  modules/mining-pipeline/prefix-span-pattern-detector/src/module-integration-test/kotlin/org/cafejojo/schaapi/miningpipeline/patterndetector/prefixspan/CCSpanJimpleNodeIntegrationTest.kt
  modules/mining-pipeline/prefix-span-pattern-detector/src/module-integration-test/kotlin/org/cafejojo/schaapi/miningpipeline/patterndetector/prefixspan/TestValues.kt
  modules/mining-pipeline/prefix-span-pattern-detector/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/patterndetector/prefixspan/PrefixSpanHelper.kt
  modules/mining-pipeline/prefix-span-pattern-detector/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/patterndetector/prefixspan/PrefixSpanTest.kt
  modules/mining-pipeline/prefix-span-pattern-detector/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/patterndetector/prefixspan/TestNodeComparator.kt
  modules/mining-pipeline/spam-pattern-detector/build.gradle
  modules/mining-pipeline/spam-pattern-detector/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/patterndetector/spam/Spam.kt
  modules/mining-pipeline/spam-pattern-detector/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/patterndetector/spam/SpamPatternDetector.kt
  modules/mining-pipeline/spam-pattern-detector/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/patterndetector/spam/SpamTest.kt
  modules/mining-pipeline/spam-pattern-detector/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/patterndetector/spam/TestNodeComparator.kt
  settings.gradle
Labels: code quality

#281 Refactor generalizedValuesAreEqual
  modules/models/jimple-library-usage-graph/src/main/kotlin/org/cafejojo/schaapi/models/libraryusagegraph/jimple/GeneralizedNodeComparator.kt
Labels: code quality

#276 Filter out user-project usages from all kinds of statements
  modules/mining-pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/JimpleLibraryUsageGraphGenerator.kt
  modules/mining-pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/filters/StatementFilter.kt
  modules/mining-pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/filters/ValueFilter.kt
  modules/mining-pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/processors/Processor.kt
  modules/mining-pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/processors/UserUsageProcessor.kt
  modules/mining-pipeline/jimple-library-usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/filters/Helpers.kt
  modules/mining-pipeline/jimple-library-usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/filters/StatementFilterTest.kt
  modules/mining-pipeline/jimple-library-usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/filters/ValueFilterTest.kt
  modules/mining-pipeline/jimple-library-usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/processors/UserUsageProcessorTest.kt
Labels: bug

#290 Use snapshot release of Jacoco
  build.gradle
  gradle.properties
Labels: tooling

#296 Bump version number to 1.0.0-RC1
  gradle.properties
Labels: documentation

#297 Add task to build mining pipeline fat JAR
  modules/application/build.gradle
Labels: tooling

#292 Suppress warning about unused `of` parameter
  modules/validation-pipeline/github-interactor/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/githubinteractor/githubapi/JsonObjectBuilder.kt
Labels: code quality

#299 Filter lambdas
  modules/mining-pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/filters/ValueFilter.kt
  modules/mining-pipeline/jimple-library-usage-graph-generator/src/test/java/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/testclasses/library/LibrarySupplier.java
  modules/mining-pipeline/jimple-library-usage-graph-generator/src/test/java/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/testclasses/library/Object1.java
  modules/mining-pipeline/jimple-library-usage-graph-generator/src/test/java/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/testclasses/users/LambdaClassConstantTest.java
  modules/mining-pipeline/jimple-library-usage-graph-generator/src/test/java/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/testclasses/users/LambdaUsageTest.java
  modules/mining-pipeline/jimple-library-usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/IntegrationTest.kt
  modules/mining-pipeline/jimple-library-usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/filters/ValueFilterTest.kt
Labels: bug

#300 Do not require Codecov checks to pass
  codecov.yml
Labels: tooling

#302 Distinguish integration test classes
  modules/mining-pipeline/jimple-library-usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/JimpleUsageGraphGeneratorIntegrationTest.kt
  modules/validation-pipeline/ci-job/src/test/kotlin/org/cafejojo/schaapi/validationpipeline/cijob/CIJobIntegrationTest.kt
  modules/validation-pipeline/github-interactor/src/test/kotlin/org/cafejojo/schaapi/validationpipeline/githubinteractor/GitHubInteractorIntegrationTest.kt
Labels: code quality

#304 Rename RegressionTest to Patterns
  modules/application/src/module-integration-test/kotlin/org/cafejojo/schaapi/SchaapiSmokeTest.kt
  modules/mining-pipeline/jimple-evosuite-test-generator/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/testgenerator/jimpleevosuite/TestGenerator.kt
  modules/validation-pipeline/ci-job/src/test/kotlin/org/cafejojo/schaapi/validationpipeline/cijob/CIJobTest.kt
  modules/validation-pipeline/ci-job/src/test/resources/projects/cafejojo/dummy-simple-maven-library/failing-tests/FailingPatterns_ESTest.java
  modules/validation-pipeline/ci-job/src/test/resources/projects/cafejojo/dummy-simple-maven-library/tests-construction/Patterns.java
  modules/validation-pipeline/ci-job/src/test/resources/projects/cafejojo/dummy-simple-maven-library/tests/Patterns.class
  modules/validation-pipeline/ci-job/src/test/resources/projects/cafejojo/dummy-simple-maven-library/tests/Patterns_ESTest.java
  modules/validation-pipeline/ci-job/src/test/resources/projects/cafejojo/dummy-simple-maven-library/tests/RegressionTest.class
Labels: enhancement

#303 Let evosuite create 1 file per test
  modules/application/src/module-integration-test/kotlin/org/cafejojo/schaapi/SchaapiSmokeTest.kt
  modules/mining-pipeline/jimple-evosuite-test-generator/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/testgenerator/jimpleevosuite/EvosuiteTestGenerator.kt
  modules/mining-pipeline/jimple-evosuite-test-generator/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/testgenerator/jimpleevosuite/EvoSuiteRunnerTest.kt
Labels: enhancement

#308 Make CI job truly asynchronous
  modules/validation-pipeline/ci-job/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/cijob/CIJob.kt
  modules/validation-pipeline/ci-job/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/cijob/CIJobInitiator.kt
  modules/validation-pipeline/ci-job/src/test/kotlin/org/cafejojo/schaapi/validationpipeline/cijob/CIJobIntegrationTest.kt
  modules/validation-pipeline/ci-job/src/test/kotlin/org/cafejojo/schaapi/validationpipeline/cijob/CIJobTest.kt
Labels: bug

#235 Usage count filter
  modules/application/src/main/kotlin/org/cafejojo/schaapi/CommandLineInterface.kt
  modules/application/src/main/kotlin/org/cafejojo/schaapi/DirectoryMiningCommandLineInterface.kt
  modules/application/src/main/kotlin/org/cafejojo/schaapi/GitHubMiningCommandLineInterface.kt
  modules/mining-pipeline/jimple-pattern-filter/build.gradle
  modules/mining-pipeline/jimple-pattern-filter/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/patternfilter/jimple/InsufficientLibraryUsageFilterRule.kt
  modules/mining-pipeline/jimple-pattern-filter/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/patternfilter/jimple/InsufficientLibraryUsageFilterRuleTest.kt
Labels: enhancement

#285 Add CSV writer to pipeline
  modules/application/src/main/kotlin/org/cafejojo/schaapi/DirectoryMiningCommandLineInterface.kt
  modules/application/src/main/kotlin/org/cafejojo/schaapi/GitHubMiningCommandLineInterface.kt
  modules/mining-pipeline/ccspan-pattern-detector/src/module-integration-test/kotlin/org/cafejojo/schaapi/miningpipeline/patterndetector/ccspan/CCSpanIntegrationTest.kt
  modules/mining-pipeline/java-maven-project-compiler/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/projectcompiler/javamaven/JavaMavenProjectCompiler.kt
  modules/mining-pipeline/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/CsvWriter.kt
  modules/mining-pipeline/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/MiningPipeline.kt
Labels: enhancement

#310 Practically ignore Codecov checks
  codecov.yml
Labels: tooling

#307 Write library compilation output to logger
  modules/application/src/main/kotlin/org/cafejojo/schaapi/DirectoryMiningCommandLineInterface.kt
  modules/mining-pipeline/java-maven-project-compiler/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/projectcompiler/javamaven/JavaMavenProjectCompiler.kt
Labels: enhancement

#311 Log log messages to file as well
  modules/application/src/main/resources/logback.xml
Labels: enhancement

#305 Trace tests to pattern source
  modules/validation-pipeline/testable-source-finder/build.gradle
  modules/validation-pipeline/testable-source-finder/gradle.properties
  modules/validation-pipeline/testable-source-finder/src/main/kotlin/org/cafejojo/validationpipeline/testablesourcefinder/Decompiler.kt
  modules/validation-pipeline/testable-source-finder/src/main/kotlin/org/cafejojo/validationpipeline/testablesourcefinder/MethodSourceRetriever.kt
  modules/validation-pipeline/testable-source-finder/src/main/kotlin/org/cafejojo/validationpipeline/testablesourcefinder/PatternNameFinder.kt
  modules/validation-pipeline/testable-source-finder/src/main/kotlin/org/cafejojo/validationpipeline/testablesourcefinder/TestableSourceFinder.kt
  modules/validation-pipeline/testable-source-finder/src/test/kotlin/org/cafejojo/validationpipeline/testablesourcefinder/DecompilerTest.kt
  modules/validation-pipeline/testable-source-finder/src/test/kotlin/org/cafejojo/validationpipeline/testablesourcefinder/MethodSourceRetrieverTest.kt
  modules/validation-pipeline/testable-source-finder/src/test/kotlin/org/cafejojo/validationpipeline/testablesourcefinder/PatternNameFinderTest.kt
  modules/validation-pipeline/testable-source-finder/src/test/kotlin/org/cafejojo/validationpipeline/testablesourcefinder/TestableSourceFinderTest.kt
  modules/validation-pipeline/testable-source-finder/src/test/resources/DecompiledPatterns.java
  modules/validation-pipeline/testable-source-finder/src/test/resources/Patterns.class
  modules/validation-pipeline/testable-source-finder/src/test/resources/Patterns_ESTest.java
  modules/validation-pipeline/testable-source-finder/src/test/resources/non-class-file.txt
  settings.gradle
Labels: enhancement

#309 CLI unduplication
  modules/application/src/main/kotlin/org/cafejojo/schaapi/CommandLineInterface.kt
  modules/application/src/main/kotlin/org/cafejojo/schaapi/DirectoryMiningCommandLineInterface.kt
  modules/application/src/main/kotlin/org/cafejojo/schaapi/GitHubMiningCommandLineInterface.kt
  modules/application/src/main/kotlin/org/cafejojo/schaapi/OptionSets.kt
  modules/application/src/module-integration-test/kotlin/org/cafejojo/schaapi/SchaapiSmokeTest.kt
Labels: code quality

#316 Add accuracy disclaimer to test results
  modules/validation-pipeline/github-interactor/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/githubinteractor/CIJobCompletedListener.kt
Labels: enhancement

#315 Only log error messages to the console
  modules/application/src/main/resources/logback.xml
  modules/mining-pipeline/java-maven-project-compiler/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/projectcompiler/javamaven/JavaMavenProjectCompiler.kt
Labels: enhancement

#313 Include patterns in check reports
  modules/validation-pipeline/github-interactor/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/githubinteractor/CIJobCompletedListener.kt
  modules/validation-pipeline/github-interactor/src/test/kotlin/org/cafejojo/schaapi/validationpipeline/githubinteractor/CIJobCompletedListenerTest.kt
  modules/validation-pipeline/github-interactor/src/test/kotlin/org/cafejojo/schaapi/validationpipeline/githubinteractor/GitHubInteractorIntegrationTest.kt
  modules/validation-pipeline/gradle.properties
  modules/validation-pipeline/junit-test-runner/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/testrunner/junit/TestRunner.kt
  modules/validation-pipeline/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/TestRunner.kt
  modules/validation-pipeline/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/TestableSourceFinder.kt
  modules/validation-pipeline/testable-source-finder/build.gradle
  modules/validation-pipeline/testable-source-finder/gradle.properties
  modules/validation-pipeline/testable-source-finder/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/testablesourcefinder/Decompiler.kt
  modules/validation-pipeline/testable-source-finder/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/testablesourcefinder/MethodSourceRetriever.kt
  modules/validation-pipeline/testable-source-finder/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/testablesourcefinder/PatternNameFinder.kt
  modules/validation-pipeline/testable-source-finder/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/testablesourcefinder/SingleTestPerFileTestableSourceFinder.kt
  modules/validation-pipeline/testable-source-finder/src/test/kotlin/org/cafejojo/schaapi/validationpipeline/testablesourcefinder/DecompilerTest.kt
  modules/validation-pipeline/testable-source-finder/src/test/kotlin/org/cafejojo/schaapi/validationpipeline/testablesourcefinder/MethodSourceRetrieverTest.kt
  modules/validation-pipeline/testable-source-finder/src/test/kotlin/org/cafejojo/schaapi/validationpipeline/testablesourcefinder/PatternNameFinderTest.kt
  modules/validation-pipeline/testable-source-finder/src/test/kotlin/org/cafejojo/schaapi/validationpipeline/testablesourcefinder/TestableSourceFinderTest.kt
  modules/web/build.gradle
Labels: enhancement

#306 Handle IOException when opening InputStream to download GitHub project
  modules/mining-pipeline/github-project-miner/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/miner/github/GitHubProjectDownloader.kt
  modules/mining-pipeline/github-project-miner/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/miner/github/GitHubProjectDownloaderTest.kt
Labels: bug
