Repository cafejojo/schaapi, pull requests merged in 2018-05, with the labels that each got.

#10 Disable Travis email notifications
  .travis.yml
Labels: tooling

#12 Set up AppVeyor
  README.md
  appveyor.yml
Labels: tooling

#14 Set up Detekt
  .travis.yml
  appveyor.yml
  build.gradle
  config/detekt/detekt-config.yml
  gradle.properties
  gradle/detekt.gradle
  src/main/kotlin/org/cafejojo/schaapi/Schaapi.kt
  subprojects/pattern-detector/src/main/kotlin/org/cafejojo/schaapi/patterndetector/PatternDetector.kt
  subprojects/usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/usagegraphgenerator/InstructionGrouper.kt
  subprojects/usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/usagegraphgenerator/UsageGraphGenerator.kt
Labels: tooling

#13 Implement enumeration of all simple paths in a CFG
  subprojects/pattern-detector/build.gradle
  subprojects/pattern-detector/src/main/kotlin/org/cafejojo/schaapi/patterndetector/PathEnumerator.kt
  subprojects/pattern-detector/src/test/kotlin/org/cafejojo/schaapi/patterndetector/PathEnumeratorTest.kt
Labels: enhancement

#11 Add DOT graph renderer
  config/detekt/detekt-config.yml
  subprojects/usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/usagegraphgenerator/DotGraphRenderer.kt
  subprojects/usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/usagegraphgenerator/Node.kt
  subprojects/usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/usagegraphgenerator/DotGraphRendererTest.kt
Labels: enhancement

#19 Move Detekt config to root
  detekt.yml
  gradle/detekt.gradle
Labels: tooling

#18 Add first version of Prefix Space Algorithm
  subprojects/pattern-detector/src/main/kotlin/org/cafejojo/schaapi/patterndetector/PatternDetector.kt
  subprojects/pattern-detector/src/test/kotlin/org/cafejojo/schaapi/patterndetector/PatternDetectorTest.kt
Labels: enhancement

#9 Codecov
  .travis.yml
  README.md
  build.gradle
Labels: tooling

#24 Add statement and value filters
  subprojects/pattern-detector/build.gradle
  subprojects/usage-graph-generator/build.gradle
  subprojects/usage-graph-generator/gradle.properties
  subprojects/usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/usagegraphgenerator/filters/StatementFilter.kt
  subprojects/usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/usagegraphgenerator/filters/ValueFilter.kt
  subprojects/usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/usagegraphgenerator/filters/StatementFilterTest.kt
  subprojects/usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/usagegraphgenerator/filters/ValueFilterTest.kt
Labels: enhancement

#23 Project class resolver
  subprojects/project-compiler/src/main/kotlin/org/cafejojo/schaapi/projectcompiler/JavaMavenProject.kt
  subprojects/project-compiler/src/main/kotlin/org/cafejojo/schaapi/projectcompiler/JavaProject.kt
  subprojects/project-compiler/src/main/kotlin/org/cafejojo/schaapi/projectcompiler/ProjectCompiler.kt
  subprojects/project-compiler/src/test/kotlin/org/cafejojo/schaapi/projectcompiler/JavaMavenProjectTest.kt
  subprojects/project-compiler/src/test/resources/Project/dependencies-classes/pom.xml
  subprojects/project-compiler/src/test/resources/Project/dependencies-classes/src/main/java/org/cafejojo/schaapi/test/MyClass.java
Labels: enhancement

#20 Count sequence occurence
  subprojects/pattern-detector/src/main/kotlin/org/cafejojo/schaapi/patterndetector/PatternDetector.kt
  subprojects/pattern-detector/src/test/kotlin/org/cafejojo/schaapi/patterndetector/PathEnumeratorTest.kt
  subprojects/pattern-detector/src/test/kotlin/org/cafejojo/schaapi/patterndetector/PatternDetectorTest.kt
Labels: enhancement

#28 Use `for-the-badge` style for Shields.io badges
  README.md
Labels: good first issue

#29 ➕ ❤️ 2️⃣ 📝
  README.md
Labels: good first issue

#25 Add Soot-based statement control flow graphs
  build.gradle
  settings.gradle
  subprojects/common/build.gradle
  subprojects/common/src/main/kotlin/org/cafejojo/schaapi/common/Node.kt
  subprojects/pattern-detector/build.gradle
  subprojects/pattern-detector/src/main/kotlin/org/cafejojo/schaapi/patterndetector/PathEnumerator.kt
  subprojects/pattern-detector/src/main/kotlin/org/cafejojo/schaapi/patterndetector/PatternDetector.kt
  subprojects/pattern-detector/src/test/kotlin/org/cafejojo/schaapi/patterndetector/PathEnumeratorTest.kt
  subprojects/pattern-detector/src/test/kotlin/org/cafejojo/schaapi/patterndetector/PatternDetectorTest.kt
  subprojects/project-compiler/build.gradle
  subprojects/usage-graph-generator/build.gradle
  subprojects/usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/usagegraphgenerator/ControlFlowGraphCreator.kt
  subprojects/usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/usagegraphgenerator/DotGraphRenderer.kt
  subprojects/usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/usagegraphgenerator/InstructionGrouper.kt
  subprojects/usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/usagegraphgenerator/Node.kt
  subprojects/usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/usagegraphgenerator/SootNode.kt
  subprojects/usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/usagegraphgenerator/UsageGraphGenerator.kt
  subprojects/usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/usagegraphgenerator/filters/ValueFilter.kt
  subprojects/usage-graph-generator/src/test/java/org/cafejojo/schaapi/usagegraphgenerator/testclasses/users/SimpleTest.java
  subprojects/usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/usagegraphgenerator/DotGraphRendererTest.kt
  subprojects/usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/usagegraphgenerator/InstructionGrouperTest.kt
  subprojects/usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/usagegraphgenerator/IntegrationTest.kt
  subprojects/usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/usagegraphgenerator/filters/StatementFilterTest.kt
  subprojects/usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/usagegraphgenerator/filters/ValueFilterTest.kt
Labels: enhancement

#30 🐑➡️📝
  README.md
Labels: flair

#32 Add DFS graph iterator
  subprojects/common/src/main/kotlin/org/cafejojo/schaapi/common/DfsIterator.kt
  subprojects/common/src/main/kotlin/org/cafejojo/schaapi/common/Node.kt
  subprojects/common/src/test/kotlin/org/cafejojo/schaapi/common/DfsIteratorTest.kt
Labels: enhancement

#33 Adapt path enumeration to new data structure
  subprojects/pattern-detector/src/main/kotlin/org/cafejojo/schaapi/patterndetector/PathEnumerator.kt
  subprojects/pattern-detector/src/test/kotlin/org/cafejojo/schaapi/patterndetector/PathEnumeratorTest.kt
  subprojects/pattern-detector/src/test/kotlin/org/cafejojo/schaapi/patterndetector/PatternDetectorTest.kt
  subprojects/pattern-detector/src/test/kotlin/org/cafejojo/schaapi/patterndetector/TestNode.kt
Labels: enhancement

#35 Tagginator
  detekt.yml
  subprojects/usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/usagegraphgenerator/compare/GeneralizedStmtComparator.kt
  subprojects/usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/usagegraphgenerator/compare/GeneralizedStmtComparatorHelper.kt
  subprojects/usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/usagegraphgenerator/compare/GeneralizedStmtComparatorStructureTest.kt
  subprojects/usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/usagegraphgenerator/compare/GeneralizedStmtComparatorValueTest.kt
Labels: enhancement

#34 Add if statement filter
  subprojects/usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/usagegraphgenerator/UsageGraphGenerator.kt
  subprojects/usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/usagegraphgenerator/filters/IfStatementFilter.kt
  subprojects/usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/usagegraphgenerator/filters/StatementFilter.kt
  subprojects/usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/usagegraphgenerator/filters/ValueFilter.kt
  subprojects/usage-graph-generator/src/test/java/org/cafejojo/schaapi/usagegraphgenerator/testclasses/users/IfBothUseTest.java
  subprojects/usage-graph-generator/src/test/java/org/cafejojo/schaapi/usagegraphgenerator/testclasses/users/IfFalseUseTest.java
  subprojects/usage-graph-generator/src/test/java/org/cafejojo/schaapi/usagegraphgenerator/testclasses/users/IfNoUseTest.java
  subprojects/usage-graph-generator/src/test/java/org/cafejojo/schaapi/usagegraphgenerator/testclasses/users/IfTrueUseTest.java
  subprojects/usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/usagegraphgenerator/IntegrationTest.kt
  subprojects/usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/usagegraphgenerator/filters/Helpers.kt
  subprojects/usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/usagegraphgenerator/filters/IfStatementFilterTest.kt
  subprojects/usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/usagegraphgenerator/filters/StatementFilterTest.kt
  subprojects/usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/usagegraphgenerator/filters/ValueFilterTest.kt
Labels: enhancement

#39 Run EvoSuite in new process
  settings.gradle
  subprojects/test-generator/build.gradle
  subprojects/test-generator/gradle.properties
  subprojects/test-generator/src/main/kotlin/org/cafejojo/schaapi/testgenerator/EvoSuiteRunner.kt
  subprojects/test-generator/src/main/kotlin/org/cafejojo/schaapi/testgenerator/TestGenerator.kt
  subprojects/test-generator/src/test/java/org/cafejojo/schaapi/test/EvoSuiteTestClass.java
  subprojects/test-generator/src/test/kotlin/org/cafejojo/schaapi/testgenerator/EvoSuiteRunnerTest.kt
Labels: enhancement

#42 Explicitly set JAVA_HOME in Maven project compilation
  subprojects/project-compiler/src/main/kotlin/org/cafejojo/schaapi/projectcompiler/JavaMavenProject.kt
Labels: bug

#43 Add a class for writing SootClasses to .class files
  subprojects/test-generator/build.gradle
  subprojects/test-generator/gradle.properties
  subprojects/test-generator/src/main/kotlin/org/cafejojo/schaapi/testgenerator/SootClassWriter.kt
  subprojects/test-generator/src/test/kotlin/org/cafejojo/schaapi/testgenerator/SootClassWriterTest.kt
Labels: enhancement

#45 Use OS temporary dirs to store SUT files in
  subprojects/common/src/main/kotlin/org/cafejojo/schaapi/common/JavaProject.kt
  subprojects/project-compiler/src/main/kotlin/org/cafejojo/schaapi/projectcompiler/JavaMavenProject.kt
  subprojects/project-compiler/src/test/kotlin/org/cafejojo/schaapi/projectcompiler/JavaMavenProjectTest.kt
  subprojects/project-compiler/src/test/kotlin/org/cafejojo/schaapi/projectcompiler/MavenInstallerTest.kt
Labels: bug, enhancement

#41 Generate a Soot method from sequence of Soot Statements
  subprojects/test-generator/build.gradle
  subprojects/test-generator/src/main/kotlin/org/cafejojo/schaapi/testgenerator/SootClassGenerator.kt
  subprojects/test-generator/src/test/kotlin/org/cafejojo/schaapi/testgenerator/SootClassGeneratorTest.kt
Labels: enhancement

#44 Add support for filtering switch statements
  subprojects/usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/usagegraphgenerator/SootProjectLibraryUsageGraphGenerator.kt
  subprojects/usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/usagegraphgenerator/filters/BranchStatementFilter.kt
  subprojects/usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/usagegraphgenerator/filters/IfStatementFilter.kt
  subprojects/usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/usagegraphgenerator/filters/StatementFilter.kt
  subprojects/usage-graph-generator/src/test/java/org/cafejojo/schaapi/usagegraphgenerator/testclasses/users/SwitchDefaultUseTest.java
  subprojects/usage-graph-generator/src/test/java/org/cafejojo/schaapi/usagegraphgenerator/testclasses/users/SwitchNoUseTest.java
  subprojects/usage-graph-generator/src/test/java/org/cafejojo/schaapi/usagegraphgenerator/testclasses/users/SwitchOneUseTest.java
  subprojects/usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/usagegraphgenerator/IntegrationTest.kt
  subprojects/usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/usagegraphgenerator/filters/IfStatementFilterTest.kt
Labels: enhancement

#47 Implement a number of class-generator fixes
  subprojects/test-generator/src/main/kotlin/org/cafejojo/schaapi/testgenerator/SootClassGenerator.kt
  subprojects/test-generator/src/test/kotlin/org/cafejojo/schaapi/testgenerator/SootClassGeneratorTest.kt
Labels: bug

#48 Add parameter to write EvoSuite errors to
  subprojects/test-generator/src/main/kotlin/org/cafejojo/schaapi/testgenerator/EvoSuiteRunner.kt
Labels: enhancement

#49 Add CI logos to build status badges
  README.md
Labels: flair

#50 Fix Codecov capitalisation
  README.md
Labels: flair

#52 More Soot class generator fixes
  subprojects/test-generator/src/main/kotlin/org/cafejojo/schaapi/testgenerator/EvoSuiteRunner.kt
  subprojects/test-generator/src/main/kotlin/org/cafejojo/schaapi/testgenerator/SootClassGenerator.kt
Labels: bug

#53 Move equals to SootNode class
  subprojects/usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/usagegraphgenerator/SootNode.kt
  subprojects/usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/usagegraphgenerator/compare/GeneralizedSootComparator.kt
  subprojects/usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/usagegraphgenerator/SootNodeTest.kt
  subprojects/usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/usagegraphgenerator/compare/GeneralizedSootComparatorStructureTest.kt
Labels: enhancement

#58 Integrate all modules into pipeline
  build.gradle
  gradle.properties
  src/main/kotlin/org/cafejojo/schaapi/Schaapi.kt
  src/test/kotlin/org/cafejojo/schaapi/SchaapiSmokeTest.kt
  src/test/kotlin/org/cafejojo/schaapi/SchaapiTest.kt
  src/test/resources/library/pom.xml
  src/test/resources/library/src/main/java/org/cafejojo/schaapi/test/library/LibraryClass.java
  src/test/resources/user/a/lib/org/cafejojo/schaapi/test/library/1.0.0/library-1.0.0.jar
  src/test/resources/user/a/pom.xml
  src/test/resources/user/a/src/main/java/org/cafejojo/schaapi/test/user/a/UserClass.java
  subprojects/project-compiler/build.gradle
  subprojects/project-compiler/gradle.properties
  subprojects/project-compiler/src/main/kotlin/org/cafejojo/schaapi/projectcompiler/MavenInstaller.kt
  subprojects/test-generator/src/main/kotlin/org/cafejojo/schaapi/testgenerator/SootClassGenerator.kt
  subprojects/test-generator/src/test/kotlin/org/cafejojo/schaapi/testgenerator/SootClassGeneratorTest.kt
Labels: enhancement

#59 Remove main methods
  build.gradle
  subprojects/pattern-detector/build.gradle
  subprojects/pattern-filter/build.gradle
  subprojects/project-compiler/build.gradle
  subprojects/project-compiler/src/main/kotlin/org/cafejojo/schaapi/projectcompiler/JavaMavenProject.kt
  subprojects/test-generator/build.gradle
  subprojects/test-generator/src/main/kotlin/org/cafejojo/schaapi/testgenerator/TestGenerator.kt
  subprojects/usage-graph-generator/build.gradle
  subprojects/usage-graph-generator/gradle.properties
  subprojects/usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/usagegraphgenerator/SootProjectLibraryUsageGraphGenerator.kt
Labels: enhancement

#61 Fix unbound variables check
  subprojects/test-generator/src/main/kotlin/org/cafejojo/schaapi/testgenerator/SootClassGenerator.kt
Labels: bug

#62 Add .editorconfig and fix code style violations
  .editorconfig
  subprojects/project-compiler/src/test/resources/Project/dependencies-classes/src/main/java/org/cafejojo/schaapi/test/MyClass.java
  subprojects/test-generator/src/test/kotlin/org/cafejojo/schaapi/testgenerator/EvoSuiteRunnerTest.kt
  subprojects/usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/usagegraphgenerator/DotGraphRendererTest.kt
Labels: code quality

#60 Add length pattern filter
  src/main/kotlin/org/cafejojo/schaapi/Schaapi.kt
  subprojects/pattern-filter/src/main/kotlin/org/cafejojo/schaapi/patternfilter/IncompleteInitPatternFilter.kt
  subprojects/pattern-filter/src/main/kotlin/org/cafejojo/schaapi/patternfilter/LengthPatternFilter.kt
  subprojects/pattern-filter/src/test/kotlin/org/cafejojo/schaapi/patternfilter/IncompleteInitPatternFilterTest.kt
  subprojects/pattern-filter/src/test/kotlin/org/cafejojo/schaapi/patternfilter/LengthPatternFilterTest.kt
  subprojects/pattern-filter/src/test/kotlin/org/cafejojo/schaapi/patternfilter/TestNode.kt
Labels: enhancement

#54 Prefix span and tagginator integrator
  src/main/kotlin/org/cafejojo/schaapi/Schaapi.kt
  subprojects/pattern-detector/build.gradle
  subprojects/pattern-detector/gradle.properties
  subprojects/pattern-detector/src/main/kotlin/org/cafejojo/schaapi/patterndetector/PatternDetector.kt
  subprojects/pattern-detector/src/test/kotlin/org/cafejojo/schaapi/patterndetector/PatternDetectorAndSootComparatorTest.kt
  subprojects/pattern-detector/src/test/kotlin/org/cafejojo/schaapi/patterndetector/PatternDetectorHelper.kt
  subprojects/pattern-detector/src/test/kotlin/org/cafejojo/schaapi/patterndetector/PatternDetectorTest.kt
  subprojects/pattern-detector/src/test/kotlin/org/cafejojo/schaapi/patterndetector/TestNodeComparator.kt
Labels: enhancement

#80 Change JimpleNode's unit to a statement
  modules/models/jimple-library-usage-graph/src/main/kotlin/org/cafejojo/schaapi/models/libraryusagegraph/jimple/JimpleNode.kt
  modules/models/jimple-library-usage-graph/src/main/kotlin/org/cafejojo/schaapi/models/libraryusagegraph/jimple/compare/GeneralizedSootComparator.kt
  modules/pipeline/jimple-evosuite-test-generator/src/main/kotlin/org/cafejojo/schaapi/testgenerator/jimpleevosuite/TestableGenerator.kt
  modules/pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/usagegraphgenerator/jimple/ControlFlowGraphGenerator.kt
  modules/pipeline/jimple-library-usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/usagegraphgenerator/jimple/IntegrationTest.kt
  modules/pipeline/jimple-pattern-filter/src/main/kotlin/org/cafejojo/schaapi/patternfilter/jimple/IncompleteInitPatternFilter.kt
Labels: code quality

#76 Add interface for test generation and move test generation logic away from Schaapi class
  modules/common/src/main/kotlin/org/cafejojo/schaapi/common/Pattern.kt
  modules/common/src/main/kotlin/org/cafejojo/schaapi/common/TestGenerator.kt
  modules/pipeline/jimple-evosuite-test-generator/src/main/kotlin/org/cafejojo/schaapi/testgenerator/jimpleevosuite/EvosuiteTestGenerator.kt
  modules/pipeline/jimple-evosuite-test-generator/src/main/kotlin/org/cafejojo/schaapi/testgenerator/jimpleevosuite/TestGenerator.kt
  modules/pipeline/jimple-evosuite-test-generator/src/test/kotlin/org/cafejojo/schaapi/testgenerator/jimpleevosuite/TestGeneratorTest.kt
  src/main/kotlin/org/cafejojo/schaapi/Schaapi.kt
Labels: code quality

#83 Restructure pattern filters
  modules/common/src/main/kotlin/org/cafejojo/schaapi/common/PatternFilter.kt
  modules/common/src/main/kotlin/org/cafejojo/schaapi/common/PatternFilterRule.kt
  modules/common/src/test/kotlin/org/cafejojo/schaapi/common/PatternFilterTest.kt
  modules/pipeline/jimple-pattern-filter/src/main/kotlin/org/cafejojo/schaapi/patternfilter/jimple/IncompleteInitPatternFilterRule.kt
  modules/pipeline/jimple-pattern-filter/src/main/kotlin/org/cafejojo/schaapi/patternfilter/jimple/LengthPatternFilterRule.kt
  modules/pipeline/jimple-pattern-filter/src/test/kotlin/org/cafejojo/schaapi/patternfilter/jimple/IncompleteInitPatternFilterRuleTest.kt
  modules/pipeline/jimple-pattern-filter/src/test/kotlin/org/cafejojo/schaapi/patternfilter/jimple/LengthPatternFilterRuleTest.kt
  src/main/kotlin/org/cafejojo/schaapi/Schaapi.kt
Labels: code quality

#82 Move compiler to its own class and add interface
  build.gradle
  modules/common/src/main/kotlin/org/cafejojo/schaapi/common/LibraryUsageGraphGenerator.kt
  modules/common/src/main/kotlin/org/cafejojo/schaapi/common/Project.kt
  modules/common/src/main/kotlin/org/cafejojo/schaapi/common/ProjectCompiler.kt
  modules/models/java-maven-project/build.gradle
  modules/models/java-maven-project/gradle.properties
  modules/models/java-maven-project/src/main/kotlin/org/cafejojo/schaapi/project/javamaven/JavaMavenProject.kt
  modules/models/java-maven-project/src/main/kotlin/org/cafejojo/schaapi/project/javamaven/JavaProject.kt
  modules/models/java-maven-project/src/main/kotlin/org/cafejojo/schaapi/project/javamaven/MavenProject.kt
  modules/pipeline/java-maven-project-compiler/build.gradle
  modules/pipeline/java-maven-project-compiler/src/main/kotlin/org/cafejojo/schaapi/projectcompiler/javamaven/JavaMavenProject.kt
  modules/pipeline/java-maven-project-compiler/src/main/kotlin/org/cafejojo/schaapi/projectcompiler/javamaven/MavenInstaller.kt
  modules/pipeline/java-maven-project-compiler/src/main/kotlin/org/cafejojo/schaapi/projectcompiler/javamaven/ProjectCompiler.kt
  modules/pipeline/java-maven-project-compiler/src/test/kotlin/org/cafejojo/schaapi/projectcompiler/javamaven/ProjectCompilerTest.kt
  modules/pipeline/jimple-evosuite-test-generator/build.gradle
  modules/pipeline/jimple-evosuite-test-generator/src/main/kotlin/org/cafejojo/schaapi/testgenerator/jimpleevosuite/TestGenerator.kt
  modules/pipeline/jimple-library-usage-graph-generator/build.gradle
  modules/pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/usagegraphgenerator/jimple/LibraryUsageGraphGenerator.kt
  modules/pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/usagegraphgenerator/jimple/filters/BranchStatementFilter.kt
  modules/pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/usagegraphgenerator/jimple/filters/StatementFilter.kt
  modules/pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/usagegraphgenerator/jimple/filters/ValueFilter.kt
  modules/pipeline/jimple-library-usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/usagegraphgenerator/jimple/Helpers.kt
  settings.gradle
  src/main/kotlin/org/cafejojo/schaapi/Schaapi.kt
Labels: code quality

#89 Remove inline infix in Pipeline
  src/main/kotlin/org/cafejojo/schaapi/Pipeline.kt
Labels: code quality

#91 Change TestGenerator interface output to File
  modules/common/src/main/kotlin/org/cafejojo/schaapi/common/TestGenerator.kt
  modules/pipeline/jimple-evosuite-test-generator/src/main/kotlin/org/cafejojo/schaapi/testgenerator/jimpleevosuite/TestGenerator.kt
Labels: code quality

#93 Ignore build folder in `modules` folder
  .gitignore
Labels: code quality

#92 Unescape escaped characters in paths in smoke test
  src/test/kotlin/org/cafejojo/schaapi/SchaapiSmokeTest.kt
Labels: bug

#94 Rename Testable* to Class* in testgenerator package
  modules/common/src/main/kotlin/org/cafejojo/schaapi/common/ClassGenerator.kt
  modules/pipeline/jimple-evosuite-test-generator/src/main/kotlin/org/cafejojo/schaapi/testgenerator/jimpleevosuite/ClassGenerator.kt
  modules/pipeline/jimple-evosuite-test-generator/src/main/kotlin/org/cafejojo/schaapi/testgenerator/jimpleevosuite/ClassWriter.kt
  modules/pipeline/jimple-evosuite-test-generator/src/main/kotlin/org/cafejojo/schaapi/testgenerator/jimpleevosuite/TestGenerator.kt
  modules/pipeline/jimple-evosuite-test-generator/src/test/kotlin/org/cafejojo/schaapi/testgenerator/jimpleevosuite/ClassGeneratorTest.kt
  modules/pipeline/jimple-evosuite-test-generator/src/test/kotlin/org/cafejojo/schaapi/testgenerator/jimpleevosuite/ClassWriterTest.kt
  modules/pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/usagegraphgenerator/jimple/LibraryUsageGraphGenerator.kt
Labels: code quality

#97 Rename EvoSuiteTestGenerator to EvoSuiteRunner
  modules/pipeline/jimple-evosuite-test-generator/src/main/kotlin/org/cafejojo/schaapi/testgenerator/jimpleevosuite/EvosuiteTestGenerator.kt
  modules/pipeline/jimple-evosuite-test-generator/src/main/kotlin/org/cafejojo/schaapi/testgenerator/jimpleevosuite/TestGenerator.kt
  modules/pipeline/jimple-evosuite-test-generator/src/test/kotlin/org/cafejojo/schaapi/testgenerator/jimpleevosuite/EvoSuiteRunnerTest.kt
Labels: code quality

#96 Move src/ to modules/application
  build.gradle
  gradle.properties
  modules/application/build.gradle
  modules/application/gradle.properties
  modules/application/src/main/kotlin/org/cafejojo/schaapi/CommandLineInterface.kt
  modules/application/src/main/kotlin/org/cafejojo/schaapi/Pipeline.kt
  modules/application/src/test/kotlin/org/cafejojo/schaapi/SchaapiSmokeTest.kt
  modules/application/src/test/resources/library/pom.xml
  modules/application/src/test/resources/library/src/main/java/org/cafejojo/schaapi/test/library/LibraryClass.java
  modules/application/src/test/resources/user/a/lib/org/cafejojo/schaapi/test/library/1.0.0/library-1.0.0.jar
  modules/application/src/test/resources/user/a/pom.xml
  modules/application/src/test/resources/user/a/src/main/java/org/cafejojo/schaapi/test/user/a/UserClass.java
  settings.gradle
Labels: code quality

#75 Add integration tests for PrefixSpan and SootNodeComparator
  modules/pipeline/prefix-span-pattern-detector/src/main/kotlin/org/cafejojo/schaapi/patterndetector/prefixspan/FrequentSequenceFinder.kt
  modules/pipeline/prefix-span-pattern-detector/src/test/kotlin/org/cafejojo/schaapi/patterndetector/prefixspan/FrequentSequenceFinderAndSootComparatorTest.kt
  modules/pipeline/prefix-span-pattern-detector/src/test/kotlin/org/cafejojo/schaapi/patterndetector/prefixspan/FrequentSequenceFinderHelper.kt
  modules/pipeline/prefix-span-pattern-detector/src/test/kotlin/org/cafejojo/schaapi/patterndetector/prefixspan/FrequentSequenceFinderTest.kt
Labels: enhancement

#98 Clarify some documentation in the `common` module
  modules/common/src/main/kotlin/org/cafejojo/schaapi/common/LibraryUsageGraphGenerator.kt
  modules/common/src/main/kotlin/org/cafejojo/schaapi/common/Node.kt
  modules/common/src/main/kotlin/org/cafejojo/schaapi/common/Pattern.kt
  modules/common/src/main/kotlin/org/cafejojo/schaapi/common/PatternDetector.kt
  modules/common/src/main/kotlin/org/cafejojo/schaapi/common/PatternFilter.kt
  modules/common/src/main/kotlin/org/cafejojo/schaapi/common/PatternFilterRule.kt
  modules/common/src/main/kotlin/org/cafejojo/schaapi/common/ProjectCompiler.kt
  modules/common/src/main/kotlin/org/cafejojo/schaapi/common/TestGenerator.kt
  modules/pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/usagegraphgenerator/jimple/LibraryUsageGraphGenerator.kt
Labels: code quality

#101 Rename `getValues()` to `getTopLevelValues()`
  modules/models/jimple-library-usage-graph/src/main/kotlin/org/cafejojo/schaapi/models/libraryusagegraph/jimple/JimpleNode.kt
  modules/models/jimple-library-usage-graph/src/main/kotlin/org/cafejojo/schaapi/models/libraryusagegraph/jimple/compare/GeneralizedNodeComparator.kt
Labels: code quality

#105 Ignore all build directories
  .gitignore
Labels: code quality

#103 Add README contents
  README.md
Labels: flair

#104 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: flair

#107 Categorise modules into submodules in Gradle
  modules/application/build.gradle
  modules/pipeline/java-maven-project-compiler/build.gradle
  modules/pipeline/jimple-evosuite-test-generator/build.gradle
  modules/pipeline/jimple-library-usage-graph-generator/build.gradle
  modules/pipeline/jimple-pattern-filter/build.gradle
  modules/pipeline/prefix-span-pattern-detector/build.gradle
  settings.gradle
Labels: code quality

#108 Uncapitalise "contributors" in README.md
  README.md
Labels: flair

#109 Fix issue where no common end statement could be found
  modules/pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/filters/BranchStatementFilter.kt
  modules/pipeline/jimple-library-usage-graph-generator/src/test/java/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/testclasses/users/IfNoEndTest.java
  modules/pipeline/jimple-library-usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/IntegrationTest.kt
Labels: bug

#110 Check for references instead for equality
  modules/models/src/main/kotlin/org/cafejojo/schaapi/models/DfsIterator.kt
Labels: bug

#106 Add integration tests to Prefix-Span module
  detekt.yml
  modules/pipeline/prefix-span-pattern-detector/build.gradle
  modules/pipeline/prefix-span-pattern-detector/gradle.properties
  modules/pipeline/prefix-span-pattern-detector/src/integration-test/kotlin/org.cafejojo.schaapi.pipeline.patterndetector.prefixspan/FrequentSequenceFinderHelper.kt
  modules/pipeline/prefix-span-pattern-detector/src/integration-test/kotlin/org.cafejojo.schaapi.pipeline.patterndetector.prefixspan/PrefixSpanJimpleNodeIntegrationTest.kt
  modules/pipeline/prefix-span-pattern-detector/src/test/kotlin/org/cafejojo/schaapi/pipeline/patterndetector/prefixspan/FrequentSequenceFinderHelper.kt
Labels: code quality

#112 Pass whole-program option to Soot
  modules/pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/LibraryUsageGraphGenerator.kt
Labels: bug

#114 Move integration test config to separate file
  gradle/integration-tests.gradle
  modules/pipeline/prefix-span-pattern-detector/build.gradle
Labels: code quality

#115 Add integration tests for LUG
  modules/pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/filters/ValueFilter.kt
  modules/pipeline/jimple-library-usage-graph-generator/src/test/java/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/testclasses/library/LibraryException.java
  modules/pipeline/jimple-library-usage-graph-generator/src/test/java/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/testclasses/library/Object1.java
  modules/pipeline/jimple-library-usage-graph-generator/src/test/java/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/testclasses/users/AnnotationTest.java
  modules/pipeline/jimple-library-usage-graph-generator/src/test/java/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/testclasses/users/ArrayListAndLambdaTest.java
  modules/pipeline/jimple-library-usage-graph-generator/src/test/java/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/testclasses/users/StaticTest.java
  modules/pipeline/jimple-library-usage-graph-generator/src/test/java/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/testclasses/users/ThrowTest.java
  modules/pipeline/jimple-library-usage-graph-generator/src/test/java/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/testclasses/users/TryCatchTest.java
  modules/pipeline/jimple-library-usage-graph-generator/src/test/java/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/testclasses/users/ifconditional/IfBothUseTest.java
  modules/pipeline/jimple-library-usage-graph-generator/src/test/java/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/testclasses/users/ifconditional/IfFalseUseTest.java
  modules/pipeline/jimple-library-usage-graph-generator/src/test/java/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/testclasses/users/ifconditional/IfNoEndTest.java
  modules/pipeline/jimple-library-usage-graph-generator/src/test/java/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/testclasses/users/ifconditional/IfNoUseTest.java
  modules/pipeline/jimple-library-usage-graph-generator/src/test/java/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/testclasses/users/ifconditional/IfTrueUseTest.java
  modules/pipeline/jimple-library-usage-graph-generator/src/test/java/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/testclasses/users/switchconditional/SwitchDefaultUseTest.java
  modules/pipeline/jimple-library-usage-graph-generator/src/test/java/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/testclasses/users/switchconditional/SwitchNoUseTest.java
  modules/pipeline/jimple-library-usage-graph-generator/src/test/java/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/testclasses/users/switchconditional/SwitchOneUseTest.java
  modules/pipeline/jimple-library-usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/IntegrationTest.kt
Labels: bug, code quality, enhancement

#116 Recursive structure checking
  detekt.yml
  modules/application/src/main/kotlin/org/cafejojo/schaapi/CommandLineInterface.kt
  modules/models/jimple-library-usage-graph/src/main/kotlin/org/cafejojo/schaapi/models/libraryusagegraph/jimple/GeneralizedNodeComparator.kt
  modules/models/jimple-library-usage-graph/src/main/kotlin/org/cafejojo/schaapi/models/libraryusagegraph/jimple/JimpleNode.kt
  modules/models/jimple-library-usage-graph/src/test/kotlin/org/cafejojo/schaapi/models/libraryusagegraph/jimple/GeneralizedNodeComparatorStructureTest.kt
  modules/models/jimple-library-usage-graph/src/test/kotlin/org/cafejojo/schaapi/models/libraryusagegraph/jimple/GeneralizedNodeComparatorTest.kt
  modules/models/jimple-library-usage-graph/src/test/kotlin/org/cafejojo/schaapi/models/libraryusagegraph/jimple/GeneralizedNodeComparatorValueTest.kt
  modules/models/jimple-library-usage-graph/src/test/kotlin/org/cafejojo/schaapi/models/libraryusagegraph/jimple/JimpleNodeTest.kt
  modules/models/jimple-library-usage-graph/src/test/kotlin/org/cafejojo/schaapi/models/libraryusagegraph/jimple/SimpleSoot.kt
  modules/models/jimple-library-usage-graph/src/test/kotlin/org/cafejojo/schaapi/models/libraryusagegraph/jimple/SootMockFactory.kt
  modules/models/jimple-library-usage-graph/src/test/kotlin/org/cafejojo/schaapi/models/libraryusagegraph/jimple/compare/GeneralizedNodeComparatorStructureTest.kt
  modules/models/jimple-library-usage-graph/src/test/kotlin/org/cafejojo/schaapi/models/libraryusagegraph/jimple/compare/GeneralizedNodeComparatorValueTest.kt
  modules/models/jimple-library-usage-graph/src/test/kotlin/org/cafejojo/schaapi/models/libraryusagegraph/jimple/compare/GeneralizedStmtComparatorHelper.kt
  modules/pipeline/prefix-span-pattern-detector/src/integration-test/kotlin/org.cafejojo.schaapi.pipeline.patterndetector.prefixspan/FrequentSequenceFinderHelper.kt
  modules/pipeline/prefix-span-pattern-detector/src/integration-test/kotlin/org.cafejojo.schaapi.pipeline.patterndetector.prefixspan/PrefixSpanJimpleNodeIntegrationTest.kt
  modules/pipeline/prefix-span-pattern-detector/src/integration-test/kotlin/org/cafejojo/schaapi/pipeline/patterndetector/prefixspan/PrefixSpanJimpleNodeIntegrationTest.kt
  modules/pipeline/prefix-span-pattern-detector/src/integration-test/kotlin/org/cafejojo/schaapi/pipeline/patterndetector/prefixspan/TestValues.kt
Labels: code quality, enhancement

#122 Add tests for abstract methods in UGG module
  modules/pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/LibraryUsageGraphGenerator.kt
  modules/pipeline/jimple-library-usage-graph-generator/src/test/java/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/testclasses/users/AbstractClassTest.java
  modules/pipeline/jimple-library-usage-graph-generator/src/test/java/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/testclasses/users/InterfaceTest.java
  modules/pipeline/jimple-library-usage-graph-generator/src/test/java/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/testclasses/users/PartiallyAbstractClassTest.java
  modules/pipeline/jimple-library-usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/IntegrationTest.kt
Labels: bug

#119 Add Java JAR project model
  modules/application/build.gradle
  modules/application/src/main/kotlin/org/cafejojo/schaapi/CommandLineInterface.kt
  modules/models/java-project/build.gradle
  modules/models/java-project/gradle.properties
  modules/models/java-project/src/main/kotlin/org/cafejojo/schaapi/models/project/MavenProject.kt
  modules/models/java-project/src/main/kotlin/org/cafejojo/schaapi/models/project/java/JavaJarProject.kt
  modules/models/java-project/src/main/kotlin/org/cafejojo/schaapi/models/project/java/JavaMavenProject.kt
  modules/models/java-project/src/main/kotlin/org/cafejojo/schaapi/models/project/java/JavaProject.kt
  modules/pipeline/java-maven-project-compiler/build.gradle
  modules/pipeline/java-maven-project-compiler/src/main/kotlin/org/cafejojo/schaapi/pipeline/projectcompiler/javamaven/ProjectCompiler.kt
  modules/pipeline/java-maven-project-compiler/src/test/kotlin/org/cafejojo/schaapi/pipeline/projectcompiler/javamaven/ProjectCompilerTest.kt
  modules/pipeline/jimple-evosuite-test-generator/build.gradle
  modules/pipeline/jimple-evosuite-test-generator/src/main/kotlin/org/cafejojo/schaapi/pipeline/testgenerator/jimpleevosuite/TestGenerator.kt
  modules/pipeline/jimple-library-usage-graph-generator/build.gradle
  modules/pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/LibraryUsageGraphGenerator.kt
  modules/pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/filters/BranchStatementFilter.kt
  modules/pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/filters/StatementFilter.kt
  modules/pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/filters/ValueFilter.kt
  modules/pipeline/jimple-library-usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/Helpers.kt
  settings.gradle
Labels: enhancement

#118 Sort properties in Gradle wrapper properties file
  gradle/wrapper/gradle-wrapper.properties
Labels: code quality

#120 Add JAR project compiler
  modules/models/java-project/gradle.properties
  modules/pipeline/java-jar-project-compiler/build.gradle
  modules/pipeline/java-jar-project-compiler/src/main/kotlin/org/cafejojo/schaapi/pipeline/projectcompiler/javajar/ProjectCompiler.kt
  modules/pipeline/java-jar-project-compiler/src/test/kotlin/org/cafejojo/schaapi/pipeline/projectcompiler/javajar/ProjectCompilerTest.kt
  modules/pipeline/java-jar-project-compiler/src/test/resources/no-classes-project/pom.xml
  modules/pipeline/java-jar-project-compiler/src/test/resources/schaapi.no-classes-project-1.0.0.jar
  modules/pipeline/java-jar-project-compiler/src/test/resources/schaapi.simple-project-1.0.0.jar
  modules/pipeline/java-jar-project-compiler/src/test/resources/simple-project/pom.xml
  modules/pipeline/java-jar-project-compiler/src/test/resources/simple-project/src/main/java/org/cafejojo/schaapi/test/MyFirstClass.java
  modules/pipeline/java-jar-project-compiler/src/test/resources/simple-project/src/main/java/org/cafejojo/schaapi/test/MySecondClass.java
  modules/pipeline/java-maven-project-compiler/src/main/kotlin/org/cafejojo/schaapi/pipeline/projectcompiler/javamaven/ProjectCompiler.kt
  settings.gradle
Labels: enhancement

#121 Add loop integration tests
  modules/pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/filters/BranchStatementFilter.kt
  modules/pipeline/jimple-library-usage-graph-generator/src/test/java/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/testclasses/users/LoopContinueTest.java
  modules/pipeline/jimple-library-usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/IntegrationTest.kt
Labels: bug

#124 Change if-checks to requires in project classes
  modules/models/java-project/src/main/kotlin/org/cafejojo/schaapi/models/project/java/JavaJarProject.kt
  modules/models/java-project/src/main/kotlin/org/cafejojo/schaapi/models/project/java/JavaMavenProject.kt
Labels: code quality

#123 Add OS icons to build statuses
  README.md
Labels: flair

#125 Recursive type checking
  modules/models/jimple-library-usage-graph/src/main/kotlin/org/cafejojo/schaapi/models/libraryusagegraph/jimple/GeneralizedNodeComparator.kt
  modules/models/jimple-library-usage-graph/src/main/kotlin/org/cafejojo/schaapi/models/libraryusagegraph/jimple/JimpleNode.kt
  modules/models/jimple-library-usage-graph/src/test/kotlin/org/cafejojo/schaapi/models/libraryusagegraph/jimple/GeneralizedNodeComparatorValueTest.kt
  modules/models/jimple-library-usage-graph/src/test/kotlin/org/cafejojo/schaapi/models/libraryusagegraph/jimple/JimpleNodeTest.kt
  modules/models/jimple-library-usage-graph/src/test/kotlin/org/cafejojo/schaapi/models/libraryusagegraph/jimple/SimpleSoot.kt
Labels: enhancement

#126 Enable parallel tests in Gradle
  gradle.properties
Labels: tooling

#128 Equiv hash map
  detekt.yml
  modules/models/src/main/kotlin/org/cafejojo/schaapi/models/CustomHashCollections.kt
  modules/models/src/test/kotlin/org/cafejojo/schaapi/models/CustomHashCollectionsTest.kt
Labels: enhancement

#131 Fix typos in the README
  README.md
Labels: bug, flair

#132 Exclude transitive dependency on slf4j-simple
  modules/models/jimple-library-usage-graph/build.gradle
  modules/pipeline/jimple-evosuite-test-generator/build.gradle
  modules/pipeline/jimple-library-usage-graph-generator/build.gradle
  modules/pipeline/jimple-pattern-filter/build.gradle
  modules/pipeline/prefix-span-pattern-detector/build.gradle
Labels: enhancement

#135 Use correct POM file in project compiler
  modules/pipeline/java-maven-project-compiler/src/main/kotlin/org/cafejojo/schaapi/pipeline/projectcompiler/javamaven/ProjectCompiler.kt
Labels: bug

#133 Filter empty LUGs
  modules/pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/ControlFlowGraphGenerator.kt
  modules/pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/LibraryUsageGraphGenerator.kt
  modules/pipeline/jimple-library-usage-graph-generator/src/test/java/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/testclasses/users/EmptyPatternTest.java
  modules/pipeline/jimple-library-usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/IntegrationTest.kt
Labels: enhancement

#134 Skip maven tests while compiling a project
  modules/pipeline/java-maven-project-compiler/src/main/kotlin/org/cafejojo/schaapi/pipeline/projectcompiler/javamaven/ProjectCompiler.kt
Labels: enhancement

#139 Use OS path separator to separate user projects
  modules/application/src/main/kotlin/org/cafejojo/schaapi/CommandLineInterface.kt
  modules/application/src/test/kotlin/org/cafejojo/schaapi/SchaapiSmokeTest.kt
Labels: enhancement

#140 Change behavior of connectLeavesToExitNode
  modules/pipeline/prefix-span-pattern-detector/src/main/kotlin/org/cafejojo/schaapi/pipeline/patterndetector/prefixspan/PathEnumerator.kt
  modules/pipeline/prefix-span-pattern-detector/src/test/kotlin/org/cafejojo/schaapi/pipeline/patterndetector/prefixspan/PathEnumeratorTest.kt
Labels: enhancement

#137 The Lord of the Projects: The Two Compilers
  modules/application/src/main/kotlin/org/cafejojo/schaapi/CommandLineInterface.kt
  modules/application/src/main/kotlin/org/cafejojo/schaapi/Pipeline.kt
Labels: enhancement

#142 Gradle failure messages
  build.gradle
Labels: tooling

#144 Fix a small number of IntelliJ inspection warnings
  modules/models/java-project/src/main/kotlin/org/cafejojo/schaapi/models/project/java/JavaProject.kt
  modules/pipeline/jimple-evosuite-test-generator/src/main/kotlin/org/cafejojo/schaapi/pipeline/testgenerator/jimpleevosuite/ClassGenerator.kt
  modules/pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/ControlFlowGraphGenerator.kt
Labels: bug, code quality

#141 The Lord of the Projects: The Return of the Jar
  .gitignore
  modules/application/build.gradle
  modules/application/src/main/kotlin/org/cafejojo/schaapi/CommandLineInterface.kt
  modules/application/src/test/kotlin/org/cafejojo/schaapi/SchaapiSmokeTest.kt
  modules/application/src/test/resources/user/a/target/a-1.0.0.jar
  modules/application/src/test/resources/user/b/target/b-1.0.0.jar
  modules/pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/LibraryUsageGraphGenerator.kt
Labels: enhancement

#145 Use custom `equals` in `HashWrapper`
  modules/models/src/main/kotlin/org/cafejojo/schaapi/models/CustomEqualsCollections.kt
  modules/models/src/main/kotlin/org/cafejojo/schaapi/models/Node.kt
  modules/models/src/test/kotlin/org/cafejojo/schaapi/models/CustomEqualsCollectionsTest.kt
  modules/pipeline/prefix-span-pattern-detector/src/main/kotlin/org/cafejojo/schaapi/pipeline/patterndetector/prefixspan/FrequentSequenceFinder.kt
Labels: bug

#147 Refactor pathContainsSequence method
  modules/pipeline/prefix-span-pattern-detector/src/main/kotlin/org/cafejojo/schaapi/pipeline/patterndetector/prefixspan/FrequentSequenceFinder.kt
Labels: code quality

#146 Update mail address in README.md
  README.md
Labels: flair

#151 Disable Evosuite dependencies in generated tests
  modules/pipeline/jimple-evosuite-test-generator/src/main/kotlin/org/cafejojo/schaapi/pipeline/testgenerator/jimpleevosuite/EvosuiteTestGenerator.kt
Labels: enhancement

#150 Move PathEnumerator to models module
  modules/models/src/main/kotlin/org/cafejojo/schaapi/models/PathEnumerator.kt
  modules/models/src/test/kotlin/org/cafejojo/schaapi/models/PathEnumeratorTest.kt
  modules/pipeline/prefix-span-pattern-detector/src/main/kotlin/org/cafejojo/schaapi/pipeline/patterndetector/prefixspan/PatternDetector.kt
Labels: code quality

#154 Add implementation of the SPAM frequent sequence mining algorithm
  modules/models/src/main/kotlin/org/cafejojo/schaapi/models/PathUtil.kt
  modules/models/src/test/kotlin/org/cafejojo/schaapi/models/PathUtilTest.kt
  modules/models/src/test/kotlin/org/cafejojo/schaapi/models/TestNodeComparator.kt
  modules/pipeline/prefix-span-pattern-detector/src/main/kotlin/org/cafejojo/schaapi/pipeline/patterndetector/prefixspan/FrequentSequenceFinder.kt
  modules/pipeline/prefix-span-pattern-detector/src/test/kotlin/org/cafejojo/schaapi/pipeline/patterndetector/prefixspan/FrequentSequenceFinderTest.kt
  modules/pipeline/spam-pattern-detector/build.gradle
  modules/pipeline/spam-pattern-detector/src/main/kotlin/org/cafejojo/schaapi/pipeline/patterndetector/spam/FrequentSequenceFinder.kt
  modules/pipeline/spam-pattern-detector/src/main/kotlin/org/cafejojo/schaapi/pipeline/patterndetector/spam/PatternDetector.kt
  modules/pipeline/spam-pattern-detector/src/test/kotlin/org/cafejojo/schaapi/pipeline/patterndetector/spam/FrequentSequenceFinderTest.kt
  modules/pipeline/spam-pattern-detector/src/test/kotlin/org/cafejojo/schaapi/pipeline/patterndetector/spam/TestNodeComparator.kt
  settings.gradle
Labels: code quality, enhancement

#153 Filter graphs containing only meaningless statements
  modules/pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/LibraryUsageGraphGenerator.kt
Labels: enhancement

#149 Test restructure
  detekt.yml
  gradle/integration-tests.gradle
  gradle/tests/module-integration.gradle
  gradle/tests/test-configuration-generator.gradle
  modules/application/build.gradle
  modules/application/src/module-integration-test/kotlin/org/cafejojo/schaapi/SchaapiSmokeTest.kt
  modules/application/src/module-integration-test/resources/library/pom.xml
  modules/application/src/module-integration-test/resources/library/src/main/java/org/cafejojo/schaapi/test/library/LibraryClass.java
  modules/application/src/module-integration-test/resources/user/a/pom.xml
  modules/application/src/module-integration-test/resources/user/a/src/main/java/org/cafejojo/schaapi/test/user/a/UserClass.java
  modules/application/src/module-integration-test/resources/user/a/target/a-1.0.0.jar
  modules/application/src/module-integration-test/resources/user/b/pom.xml
  modules/application/src/module-integration-test/resources/user/b/src/main/java/org/cafejojo/schaapi/test/user/b/UserClass.java
  modules/application/src/module-integration-test/resources/user/b/target/b-1.0.0.jar
  modules/pipeline/prefix-span-pattern-detector/build.gradle
  modules/pipeline/prefix-span-pattern-detector/src/module-integration-test/kotlin/org/cafejojo/schaapi/pipeline/patterndetector/prefixspan/PrefixSpanJimpleNodeIntegrationTest.kt
  modules/pipeline/prefix-span-pattern-detector/src/module-integration-test/kotlin/org/cafejojo/schaapi/pipeline/patterndetector/prefixspan/TestValues.kt
Labels: code quality

#143 Add mining of GitHub Maven projects
  modules/pipeline/github-project-miner/build.gradle
  modules/pipeline/github-project-miner/gradle.properties
  modules/pipeline/github-project-miner/src/main/kotlin/org/cafejojo/schaapi/pipeline/miner/github/GithubProjectDownloader.kt
  modules/pipeline/github-project-miner/src/main/kotlin/org/cafejojo/schaapi/pipeline/miner/github/ProjectMiner.kt
  modules/pipeline/github-project-miner/src/main/kotlin/org/cafejojo/schaapi/pipeline/miner/github/SearchOptions.kt
  modules/pipeline/github-project-miner/src/test/kotlin/org/cafejojo/schaapi/pipeline/miner/github/GithubProjectDownloaderTest.kt
  modules/pipeline/github-project-miner/src/test/kotlin/org/cafejojo/schaapi/pipeline/miner/github/TestProject.kt
  modules/pipeline/github-project-miner/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
  modules/pipeline/src/main/kotlin/org/cafejojo/schaapi/pipeline/ProjectMiner.kt
  modules/pipeline/src/main/kotlin/org/cafejojo/schaapi/pipeline/SearchOptions.kt
  settings.gradle
Labels: enhancement

#152 Filter out non-library returns in branches
  modules/pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/filters/BranchStatementFilter.kt
  modules/pipeline/jimple-library-usage-graph-generator/src/test/java/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/testclasses/users/ifconditional/IfReturnsTest.java
  modules/pipeline/jimple-library-usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/IntegrationTest.kt
Labels: enhancement

#155 Set up Web module using Spring
  modules/web/build.gradle
  modules/web/gradle.properties
  modules/web/src/main/kotlin/org/cafejojo/schaapi/web/HomeController.kt
  modules/web/src/main/kotlin/org/cafejojo/schaapi/web/WebApplication.kt
  modules/web/src/main/resources/application.properties
  modules/web/src/test/kotlin/org/cafejojo/schaapi/web/HomeTest.kt
  settings.gradle
Labels: enhancement

#157 Rename bodiesTillMethodEnd -> bodiesUntil*
  modules/pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/filters/BranchStatementFilter.kt
Labels: code quality

#159 Move Java projects out of `java` package
  modules/application/src/main/kotlin/org/cafejojo/schaapi/CommandLineInterface.kt
  modules/models/java-project/src/main/kotlin/org/cafejojo/schaapi/models/project/JavaJarProject.kt
  modules/models/java-project/src/main/kotlin/org/cafejojo/schaapi/models/project/JavaMavenProject.kt
  modules/models/java-project/src/main/kotlin/org/cafejojo/schaapi/models/project/JavaProject.kt
  modules/pipeline/java-jar-project-compiler/src/main/kotlin/org/cafejojo/schaapi/pipeline/projectcompiler/javajar/ProjectCompiler.kt
  modules/pipeline/java-jar-project-compiler/src/test/kotlin/org/cafejojo/schaapi/pipeline/projectcompiler/javajar/ProjectCompilerTest.kt
  modules/pipeline/java-maven-project-compiler/src/main/kotlin/org/cafejojo/schaapi/pipeline/projectcompiler/javamaven/ProjectCompiler.kt
  modules/pipeline/java-maven-project-compiler/src/test/kotlin/org/cafejojo/schaapi/pipeline/projectcompiler/javamaven/ProjectCompilerTest.kt
  modules/pipeline/jimple-evosuite-test-generator/src/main/kotlin/org/cafejojo/schaapi/pipeline/testgenerator/jimpleevosuite/TestGenerator.kt
  modules/pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/LibraryUsageGraphGenerator.kt
  modules/pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/filters/BranchStatementFilter.kt
  modules/pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/filters/StatementFilter.kt
  modules/pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/filters/ValueFilter.kt
  modules/pipeline/jimple-library-usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/Helpers.kt
Labels: code quality

#156 Add Node Generics to Pipeline
  modules/application/src/main/kotlin/org/cafejojo/schaapi/Pipeline.kt
  modules/models/jimple-library-usage-graph/src/main/kotlin/org/cafejojo/schaapi/models/libraryusagegraph/jimple/GeneralizedNodeComparator.kt
  modules/models/jimple-library-usage-graph/src/test/kotlin/org/cafejojo/schaapi/models/libraryusagegraph/jimple/GeneralizedNodeComparatorStructureTest.kt
  modules/models/jimple-library-usage-graph/src/test/kotlin/org/cafejojo/schaapi/models/libraryusagegraph/jimple/GeneralizedNodeComparatorTest.kt
  modules/models/jimple-library-usage-graph/src/test/kotlin/org/cafejojo/schaapi/models/libraryusagegraph/jimple/GeneralizedNodeComparatorValueTest.kt
  modules/models/src/main/kotlin/org/cafejojo/schaapi/models/GeneralizedNodeComparator.kt
  modules/models/src/main/kotlin/org/cafejojo/schaapi/models/PathEnumerator.kt
  modules/models/src/main/kotlin/org/cafejojo/schaapi/models/PathUtil.kt
  modules/models/src/test/kotlin/org/cafejojo/schaapi/models/PathUtilTest.kt
  modules/models/src/test/kotlin/org/cafejojo/schaapi/models/TestNodeComparator.kt
  modules/pipeline/jimple-evosuite-test-generator/src/main/kotlin/org/cafejojo/schaapi/pipeline/testgenerator/jimpleevosuite/ClassGenerator.kt
  modules/pipeline/jimple-evosuite-test-generator/src/main/kotlin/org/cafejojo/schaapi/pipeline/testgenerator/jimpleevosuite/TestGenerator.kt
  modules/pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/LibraryUsageGraphGenerator.kt
  modules/pipeline/jimple-pattern-filter/src/main/kotlin/org/cafejojo/schaapi/pipeline/patternfilter/jimple/IncompleteInitPatternFilterRule.kt
  modules/pipeline/jimple-pattern-filter/src/main/kotlin/org/cafejojo/schaapi/pipeline/patternfilter/jimple/LengthPatternFilterRule.kt
  modules/pipeline/jimple-pattern-filter/src/test/kotlin/org/cafejojo/schaapi/pipeline/patternfilter/jimple/IncompleteInitPatternFilterRuleTest.kt
  modules/pipeline/jimple-pattern-filter/src/test/kotlin/org/cafejojo/schaapi/pipeline/patternfilter/jimple/LengthPatternFilterRuleTest.kt
  modules/pipeline/jimple-pattern-filter/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
  modules/pipeline/prefix-span-pattern-detector/src/main/kotlin/org/cafejojo/schaapi/pipeline/patterndetector/prefixspan/FrequentSequenceFinder.kt
  modules/pipeline/prefix-span-pattern-detector/src/main/kotlin/org/cafejojo/schaapi/pipeline/patterndetector/prefixspan/PatternDetector.kt
  modules/pipeline/prefix-span-pattern-detector/src/test/kotlin/org/cafejojo/schaapi/pipeline/patterndetector/prefixspan/FrequentSequenceFinderTest.kt
  modules/pipeline/prefix-span-pattern-detector/src/test/kotlin/org/cafejojo/schaapi/pipeline/patterndetector/prefixspan/TestNodeComparator.kt
  modules/pipeline/spam-pattern-detector/src/main/kotlin/org/cafejojo/schaapi/pipeline/patterndetector/spam/FrequentSequenceFinder.kt
  modules/pipeline/spam-pattern-detector/src/main/kotlin/org/cafejojo/schaapi/pipeline/patterndetector/spam/PatternDetector.kt
  modules/pipeline/spam-pattern-detector/src/test/kotlin/org/cafejojo/schaapi/pipeline/patterndetector/spam/TestNodeComparator.kt
  modules/pipeline/src/main/kotlin/org/cafejojo/schaapi/pipeline/LibraryUsageGraphGenerator.kt
  modules/pipeline/src/main/kotlin/org/cafejojo/schaapi/pipeline/Pattern.kt
  modules/pipeline/src/main/kotlin/org/cafejojo/schaapi/pipeline/PatternDetector.kt
  modules/pipeline/src/main/kotlin/org/cafejojo/schaapi/pipeline/PatternFilter.kt
  modules/pipeline/src/main/kotlin/org/cafejojo/schaapi/pipeline/PatternFilterRule.kt
  modules/pipeline/src/main/kotlin/org/cafejojo/schaapi/pipeline/TestGenerator.kt
  modules/pipeline/src/test/kotlin/org/cafejojo/schaapi/pipeline/PatternFilterTest.kt
Labels: enhancement

#162 Implement and test a directory-based project miner
  modules/pipeline/directory-project-miner/build.gradle
  modules/pipeline/directory-project-miner/gradle.properties
  modules/pipeline/directory-project-miner/src/main/kotlin/org/cafejojo/schaapi/pipeline/miner/directory/ProjectMiner.kt
  modules/pipeline/directory-project-miner/src/main/kotlin/org/cafejojo/schaapi/pipeline/miner/directory/SearchOptions.kt
  modules/pipeline/directory-project-miner/src/test/kotlin/org/cafejojo/schaapi/pipeline/miner/directory/ProjectMinerTest.kt
  modules/pipeline/directory-project-miner/src/test/resources/mixed-projects/a.project
  modules/pipeline/directory-project-miner/src/test/resources/mixed-projects/b.project
  modules/pipeline/directory-project-miner/src/test/resources/mixed-projects/project-a/project.contents
  modules/pipeline/directory-project-miner/src/test/resources/mixed-projects/project-b/project.contents
  modules/pipeline/directory-project-miner/src/test/resources/multiple-directory-projects/project-a/project.contents
  modules/pipeline/directory-project-miner/src/test/resources/multiple-directory-projects/project-b/project.contents
  modules/pipeline/directory-project-miner/src/test/resources/multiple-directory-projects/project-c/project.contents
  modules/pipeline/directory-project-miner/src/test/resources/multiple-file-projects/a.project
  modules/pipeline/directory-project-miner/src/test/resources/multiple-file-projects/b.project
  modules/pipeline/directory-project-miner/src/test/resources/multiple-file-projects/c.project
  modules/pipeline/directory-project-miner/src/test/resources/one-directory-project/project-a/project.contents
  modules/pipeline/directory-project-miner/src/test/resources/one-file-project/a.project
  settings.gradle
Labels: enhancement

#158 Add JUnit 4 test runner
  modules/pipeline/junit-test-runner/build.gradle
  modules/pipeline/junit-test-runner/gradle.properties
  modules/pipeline/junit-test-runner/src/main/kotlin/org/cafejojo/schaapi/pipeline/testrunner/junit/TestRunner.kt
  modules/pipeline/junit-test-runner/src/test/java/org/cafejojo/schaapi/pipeline/testrunner/junit/test/AnotherSimpleTest.java
  modules/pipeline/junit-test-runner/src/test/java/org/cafejojo/schaapi/pipeline/testrunner/junit/test/EmptyTest.java
  modules/pipeline/junit-test-runner/src/test/java/org/cafejojo/schaapi/pipeline/testrunner/junit/test/SimpleTest.java
  modules/pipeline/junit-test-runner/src/test/kotlin/org/cafejojo/schaapi/pipeline/testrunner/junit/TestRunnerTest.kt
  modules/pipeline/junit-test-runner/src/test/resources/a.file
  modules/pipeline/junit-test-runner/src/test/resources/directory/another.file
  modules/pipeline/junit-test-runner/src/test/resources/directory/subdirectory/yet.another.file
  modules/pipeline/src/main/kotlin/org/cafejojo/schaapi/pipeline/TestRunner.kt
  settings.gradle
Labels: enhancement

#163 Seach options typo fix
  modules/pipeline/github-project-miner/src/main/kotlin/org/cafejojo/schaapi/pipeline/miner/github/GithubProjectDownloader.kt
  modules/pipeline/github-project-miner/src/main/kotlin/org/cafejojo/schaapi/pipeline/miner/github/ProjectMiner.kt
  modules/pipeline/github-project-miner/src/main/kotlin/org/cafejojo/schaapi/pipeline/miner/github/SearchOptions.kt
  modules/pipeline/github-project-miner/src/test/kotlin/org/cafejojo/schaapi/pipeline/miner/github/GithubProjectDownloaderTest.kt
Labels: code quality

#164 Include module-integration test coverage in report
  build.gradle
  gradle/tests/test-configuration-generator.gradle
Labels: tooling

#165 Decode resource URLs for whitespace-compatibility
  modules/pipeline/directory-project-miner/src/test/kotlin/org/cafejojo/schaapi/pipeline/miner/directory/ProjectMinerTest.kt
  modules/pipeline/github-project-miner/src/main/kotlin/org/cafejojo/schaapi/pipeline/miner/github/GitHubProjectDownloader.kt
  modules/pipeline/java-jar-project-compiler/src/test/kotlin/org/cafejojo/schaapi/pipeline/projectcompiler/javajar/ProjectCompilerTest.kt
  modules/pipeline/junit-test-runner/src/test/kotlin/org/cafejojo/schaapi/pipeline/testrunner/junit/TestRunnerTest.kt
Labels: bug

#161 Add Project Generics to Pipeline
  modules/application/src/main/kotlin/org/cafejojo/schaapi/Pipeline.kt
  modules/pipeline/directory-project-miner/src/main/kotlin/org/cafejojo/schaapi/pipeline/miner/directory/ProjectMiner.kt
  modules/pipeline/directory-project-miner/src/main/kotlin/org/cafejojo/schaapi/pipeline/miner/directory/SearchOptions.kt
  modules/pipeline/directory-project-miner/src/test/kotlin/org/cafejojo/schaapi/pipeline/miner/directory/ProjectMinerTest.kt
  modules/pipeline/github-project-miner/src/main/kotlin/org/cafejojo/schaapi/pipeline/miner/github/GitHubProjectDownloader.kt
  modules/pipeline/github-project-miner/src/main/kotlin/org/cafejojo/schaapi/pipeline/miner/github/ProjectMiner.kt
  modules/pipeline/github-project-miner/src/main/kotlin/org/cafejojo/schaapi/pipeline/miner/github/SearchOptions.kt
  modules/pipeline/java-jar-project-compiler/src/main/kotlin/org/cafejojo/schaapi/pipeline/projectcompiler/javajar/ProjectCompiler.kt
  modules/pipeline/java-maven-project-compiler/src/main/kotlin/org/cafejojo/schaapi/pipeline/projectcompiler/javamaven/ProjectCompiler.kt
  modules/pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/LibraryUsageGraphGenerator.kt
  modules/pipeline/src/main/kotlin/org/cafejojo/schaapi/pipeline/LibraryUsageGraphGenerator.kt
  modules/pipeline/src/main/kotlin/org/cafejojo/schaapi/pipeline/PatternFilterRule.kt
  modules/pipeline/src/main/kotlin/org/cafejojo/schaapi/pipeline/ProjectCompiler.kt
  modules/pipeline/src/main/kotlin/org/cafejojo/schaapi/pipeline/ProjectMiner.kt
  modules/pipeline/src/main/kotlin/org/cafejojo/schaapi/pipeline/SearchOptions.kt
  modules/pipeline/src/main/kotlin/org/cafejojo/schaapi/pipeline/TestGenerator.kt
Labels: code quality

#167 Add Project Miner to Pipeline
  modules/application/build.gradle
  modules/application/src/main/kotlin/org/cafejojo/schaapi/CommandLineInterface.kt
  modules/application/src/main/kotlin/org/cafejojo/schaapi/Pipeline.kt
  modules/application/src/module-integration-test/kotlin/org/cafejojo/schaapi/SchaapiSmokeTest.kt
  modules/pipeline/directory-project-miner/src/main/kotlin/org/cafejojo/schaapi/pipeline/miner/directory/DirectorySearchOptions.kt
  modules/pipeline/directory-project-miner/src/main/kotlin/org/cafejojo/schaapi/pipeline/miner/directory/ProjectMiner.kt
  modules/pipeline/directory-project-miner/src/test/kotlin/org/cafejojo/schaapi/pipeline/miner/directory/ProjectMinerTest.kt
  modules/pipeline/github-project-miner/src/main/kotlin/org/cafejojo/schaapi/pipeline/miner/github/ProjectMiner.kt
  modules/pipeline/github-project-miner/src/main/kotlin/org/cafejojo/schaapi/pipeline/miner/github/SearchOptions.kt
  modules/pipeline/src/main/kotlin/org/cafejojo/schaapi/pipeline/ProjectMiner.kt
  modules/pipeline/src/main/kotlin/org/cafejojo/schaapi/pipeline/SearchOptions.kt
Labels: code quality, enhancement

#169 Change `Code Style` to `Code style` in CONTRIBUTING
  CONTRIBUTING.md
Labels: flair

#172 Add Dokka task to Gadle
  build.gradle
  gradle.properties
  modules/application/src/main/kotlin/org/cafejojo/schaapi/CommandLineInterface.kt
Labels: tooling

#173 Rename 'user_dirs' argument to 'user_base_dir'
  README.md
  modules/application/src/main/kotlin/org/cafejojo/schaapi/CommandLineInterface.kt
Labels: bug

#174 Point smoke test to both user project JARs
  modules/application/src/module-integration-test/kotlin/org/cafejojo/schaapi/SchaapiSmokeTest.kt
  modules/application/src/module-integration-test/resources/user/jars/a-1.0.0.jar
  modules/application/src/module-integration-test/resources/user/jars/b-1.0.0.jar
Labels: enhancement

#176 Rename PatternDetector class in prefix span module to PrefixSpan
  modules/pipeline/prefix-span-pattern-detector/src/main/kotlin/org/cafejojo/schaapi/pipeline/patterndetector/prefixspan/PatternDetector.kt
  modules/pipeline/prefix-span-pattern-detector/src/main/kotlin/org/cafejojo/schaapi/pipeline/patterndetector/prefixspan/PrefixSpan.kt
  modules/pipeline/prefix-span-pattern-detector/src/module-integration-test/kotlin/org/cafejojo/schaapi/pipeline/patterndetector/prefixspan/PatternDetectorJimpleNodeIntegrationTest.kt
  modules/pipeline/prefix-span-pattern-detector/src/test/kotlin/org/cafejojo/schaapi/pipeline/patterndetector/prefixspan/FrequentSequenceFinderTest.kt
  modules/pipeline/prefix-span-pattern-detector/src/test/kotlin/org/cafejojo/schaapi/pipeline/patterndetector/prefixspan/PrefixSpanHelper.kt
  modules/pipeline/prefix-span-pattern-detector/src/test/kotlin/org/cafejojo/schaapi/pipeline/patterndetector/prefixspan/PrefixSpanTest.kt
Labels: code quality

#179 Disable parallel builds in AppVeyor
  appveyor.yml
Labels: tooling

#170 Smoothen the pipeline
  modules/application/src/main/kotlin/org/cafejojo/schaapi/Pipeline.kt
Labels: code quality

#182 Add GitHub miner to README.md
  README.md
Labels: flair

#185 Make usagegraphgenerator module non-interface classes internal
  modules/pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/ControlFlowGraphGenerator.kt
  modules/pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/DotGraphRenderer.kt
  modules/pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/filters/BranchStatementFilter.kt
  modules/pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/filters/StatementFilter.kt
  modules/pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/pipeline/usagegraphgenerator/jimple/filters/ValueFilter.kt
Labels: code quality

#186 Logger
  build.gradle
  gradle.properties
  modules/pipeline/github-project-miner/src/main/kotlin/org/cafejojo/schaapi/pipeline/miner/github/GitHubProjectDownloader.kt
  modules/pipeline/github-project-miner/src/main/kotlin/org/cafejojo/schaapi/pipeline/miner/github/ProjectMiner.kt
  modules/pipeline/java-jar-project-compiler/src/main/kotlin/org/cafejojo/schaapi/pipeline/projectcompiler/javajar/ProjectCompiler.kt
  modules/pipeline/java-maven-project-compiler/src/main/kotlin/org/cafejojo/schaapi/pipeline/projectcompiler/javamaven/ProjectCompiler.kt
Labels: code quality, enhancement

#184 Decrease visibility of classes in Jimple EvoSuite package
  modules/pipeline/jimple-evosuite-test-generator/src/main/kotlin/org/cafejojo/schaapi/pipeline/testgenerator/jimpleevosuite/ClassGenerator.kt
  modules/pipeline/jimple-evosuite-test-generator/src/main/kotlin/org/cafejojo/schaapi/pipeline/testgenerator/jimpleevosuite/ClassWriter.kt
  modules/pipeline/jimple-evosuite-test-generator/src/main/kotlin/org/cafejojo/schaapi/pipeline/testgenerator/jimpleevosuite/EvosuiteTestGenerator.kt
Labels: code quality

#187 Wrap mined projects in JavaMavenProjects instead of JavaJarProjects
  modules/application/src/main/kotlin/org/cafejojo/schaapi/CommandLineInterface.kt
  modules/application/src/module-integration-test/kotlin/org/cafejojo/schaapi/SchaapiSmokeTest.kt
  modules/application/src/module-integration-test/resources/user/jars/a-1.0.0.jar
  modules/application/src/module-integration-test/resources/user/jars/b-1.0.0.jar
Labels: bug

#183 Decrease visibility of GitHub project miner package
  modules/pipeline/github-project-miner/src/main/kotlin/org/cafejojo/schaapi/pipeline/miner/github/GitHubProjectDownloader.kt
  modules/pipeline/java-jar-project-compiler/src/main/kotlin/org/cafejojo/schaapi/pipeline/projectcompiler/javajar/ProjectCompiler.kt
  modules/pipeline/java-maven-project-compiler/src/main/kotlin/org/cafejojo/schaapi/pipeline/projectcompiler/javamaven/ProjectCompiler.kt
Labels: code quality
