Repository cafejojo/schaapi, pull requests merged in 2018-10, with the labels that each got.

#325 Update dependencies
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
  modules/mining-pipeline/ccspan-pattern-detector/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/patterndetector/ccspan/CCSpan.kt
  modules/mining-pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/filters/BranchStatementFilter.kt
  modules/mining-pipeline/jimple-library-usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/filters/RecursiveGotoFilterTest.kt
  modules/validation-pipeline/github-interactor/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/githubinteractor/CIJobCompletedListener.kt
  modules/validation-pipeline/github-interactor/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/githubinteractor/WebHookReceiver.kt
  modules/validation-pipeline/github-interactor/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/githubinteractor/webhookevents/CheckRunEvent.kt
  modules/validation-pipeline/junit-test-runner/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/testrunner/junit/TestRunner.kt
  modules/validation-pipeline/testable-source-finder/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/testablesourcefinder/MethodSourceRetriever.kt
Labels: tooling

#319 Add library flavour option to command line
  gradle.properties
  modules/application/src/main/kotlin/org/cafejojo/schaapi/DirectoryMiningCommandLineInterface.kt
  modules/application/src/main/kotlin/org/cafejojo/schaapi/GitHubMiningCommandLineInterface.kt
  modules/application/src/main/kotlin/org/cafejojo/schaapi/OptionSets.kt
Labels: enhancement

#301 Add progress bar to the application
  modules/application/src/main/kotlin/org/cafejojo/schaapi/CommandLineInterface.kt
  modules/mining-pipeline/build.gradle
  modules/mining-pipeline/gradle.properties
  modules/mining-pipeline/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/MiningPipeline.kt
Labels: enhancement

#330 Update usage instructions in README
  README.md
Labels: flair

#332 Add mining flavor argument to CMD instructions
  README.md
Labels: documentation

#333 Remove user notification pipeline step from README
  README.md
Labels: documentation

#329 Allow skipping of compilation of user projects
  README.md
  modules/application/src/main/kotlin/org/cafejojo/schaapi/DirectoryMiningCommandLineInterface.kt
  modules/mining-pipeline/java-maven-project-compiler/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/projectcompiler/javamaven/JavaMavenProjectCompiler.kt
Labels: enhancement
