Repository cafejojo/schaapi, pull requests merged in 2018-07, with the labels that each got.

#317 Emphasise Schaapi acronym in README.md
  README.md
Labels: flair

#320 Remove incorrect logger argument
  modules/mining-pipeline/java-maven-project-compiler/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/projectcompiler/javamaven/JavaMavenProjectCompiler.kt
Labels: bug

#318 Fix appender configurability
  modules/application/src/main/resources/logback.xml
Labels: enhancement

#324 Really fix the Codecov yaml this time
  codecov.yml
Labels: tooling

#323 Update Kotlin
  gradle.properties
Labels: tooling
