Repository cafejojo/schaapi, pull requests merged in 2018-11, with the labels that each got.

#335 Disable Detekt's UnnecessaryApply rule
  detekt.yml
Labels: tooling

#336 Exclude hidden files from directory pipeline
  modules/mining-pipeline/directory-project-miner/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/miner/directory/DirectoryProjectMiner.kt
Labels: enhancement

#339 Handle Invalid Class Constants
  modules/mining-pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/filters/ValueFilter.kt
Labels: bug

#343 The return of the ASCII art
  modules/application/src/main/resources/schaapi-ascii-art.txt
Labels: flair

#340 Add test for hidden file exclusion
  modules/mining-pipeline/directory-project-miner/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/miner/directory/DirectoryProjectMinerTest.kt
  modules/mining-pipeline/directory-project-miner/src/test/resources/hidden-projects/.hiddenfile
  modules/mining-pipeline/directory-project-miner/src/test/resources/hidden-projects/a.project
Labels: code quality

#344 Clarify missing flavor argument message
  modules/application/src/main/kotlin/org/cafejojo/schaapi/CommandLineInterface.kt
Labels: code quality, flair

#346 Replace Invalid Targets in Actual Active Method Body
  modules/mining-pipeline/jimple-evosuite-test-generator/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/testgenerator/jimpleevosuite/ClassGenerator.kt
Labels: bug

#342 Move configuration files together
  .appveyor.yml
  .codecov.yml
  .detekt.yml
  gradle/detekt.gradle
Labels: tooling

#345 List possible library types in command line options
  README.md
  modules/application/src/main/kotlin/org/cafejojo/schaapi/OptionSets.kt
Labels: flair

#349 Bump Kotlin version to 1.3.0
  gradle.properties
Labels: tooling

#351 Fix logger errors
  modules/mining-pipeline/gradle.properties
  modules/mining-pipeline/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/MiningPipeline.kt
Labels: bug

#348 Improve flavor and library type explanations in README
  README.md
Labels: documentation

#353 Fix implicit references to 'it' in JLUGGenerator
  modules/mining-pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/JimpleLibraryUsageGraphGenerator.kt
Labels: code quality

#350 Fix issue with EvoSuite JAVA_HOME setup
  modules/mining-pipeline/jimple-evosuite-test-generator/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/testgenerator/jimpleevosuite/EvosuiteTestGenerator.kt
Labels: bug

#357 Enable Soot Jimple optimizations after generation
  modules/mining-pipeline/jimple-evosuite-test-generator/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/testgenerator/jimpleevosuite/ClassGenerator.kt
  modules/mining-pipeline/jimple-evosuite-test-generator/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/testgenerator/jimpleevosuite/TestGenerator.kt
  modules/mining-pipeline/jimple-evosuite-test-generator/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/testgenerator/jimpleevosuite/ClassGeneratorTest.kt
  modules/mining-pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/JimpleLibraryUsageGraphGenerator.kt
Labels: enhancement

#356 Enable EvoSuite output by default
  README.md
  modules/application/src/main/kotlin/org/cafejojo/schaapi/OptionSets.kt
Labels: enhancement
