Repository cafejojo/schaapi, pull requests merged in 2019-02, with the labels that each got.

#360 Work around Detekt SwallowedException errors
  modules/application/src/main/kotlin/org/cafejojo/schaapi/CommandLineInterface.kt
  modules/mining-pipeline/directory-project-miner/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/miner/directory/DirectoryProjectMinerTest.kt
  modules/validation-pipeline/github-interactor/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/githubinteractor/githubapi/CustomHttpClient.kt
Labels: bug, critical

#359 Output empty class if no patterns were found
  modules/mining-pipeline/jimple-evosuite-test-generator/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/testgenerator/jimpleevosuite/TestGenerator.kt
Labels: bug

#361 Delete faulty project files
  modules/mining-pipeline/github-project-miner/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/miner/github/GitHubProjectDownloader.kt
Labels: enhancement

#362 Prevent `IfStmt`s from having only one successor
  modules/mining-pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/ControlFlowGraphGenerator.kt
Labels: bug

#365 Catch LUG exceptions
  modules/mining-pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/JimpleLibraryUsageGraphGenerator.kt
  modules/mining-pipeline/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/MiningPipeline.kt
  modules/validation-pipeline/ci-job/src/main/kotlin/org/cafejojo/schaapi/validationpipeline/cijob/CIJob.kt
Labels: bug, code quality, enhancement

#366 Replace `:` with `_` during unpacking
  modules/mining-pipeline/github-project-miner/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/miner/github/GitHubProjectDownloader.kt
Labels: bug

#367 Simplify GitHub project extraction process
  modules/mining-pipeline/github-project-miner/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/miner/github/GitHubProjectDownloader.kt
  modules/mining-pipeline/github-project-miner/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/miner/github/GitHubProjectDownloaderTest.kt
Labels: bug, enhancement

#338 Make libraryProject an argument for the MiningPipeline class
  modules/application/src/main/kotlin/org/cafejojo/schaapi/DirectoryMiningCommandLineInterface.kt
  modules/application/src/main/kotlin/org/cafejojo/schaapi/GitHubMiningCommandLineInterface.kt
  modules/mining-pipeline/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/MiningPipeline.kt
Labels: code quality

#368 Add loading bar for downloading user projects
  modules/mining-pipeline/github-project-miner/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/miner/github/GitHubProjectDownloader.kt
  modules/mining-pipeline/github-project-miner/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/miner/github/GitHubProjectMiner.kt
  modules/mining-pipeline/github-project-miner/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/miner/github/GitHubProjectDownloaderTest.kt
  modules/mining-pipeline/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/MiningPipeline.kt
Labels: code quality, enhancement

#369 Parallelise evosuite
  README.md
  modules/application/src/main/kotlin/org/cafejojo/schaapi/OptionSets.kt
  modules/application/src/module-integration-test/kotlin/org/cafejojo/schaapi/SchaapiSmokeTest.kt
  modules/mining-pipeline/jimple-evosuite-test-generator/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/testgenerator/jimpleevosuite/TestGenerator.kt
Labels: enhancement

#371 Output dependency tree on absolute path
  modules/mining-pipeline/github-project-miner/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/miner/github/MavenLibraryVersionVerifier.kt
Labels: bug

#372 Allow cleaning output directory before running
  README.md
  modules/application/src/main/kotlin/org/cafejojo/schaapi/CommandLineInterface.kt
Labels: enhancement

#373 Turn off EvoSuite VFS usage
  modules/mining-pipeline/jimple-evosuite-test-generator/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/testgenerator/jimpleevosuite/EvosuiteTestGenerator.kt
Labels: enhancement

#374 Skip projects without master branch
  modules/mining-pipeline/github-project-miner/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/miner/github/GitHubProjectDownloader.kt
  modules/mining-pipeline/github-project-miner/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/miner/github/SearchOptions.kt
  modules/mining-pipeline/github-project-miner/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/miner/github/GitHubProjectDownloaderTest.kt
Labels: bug

#377 Loosen strict type requirement in miner
  modules/mining-pipeline/github-project-miner/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/miner/github/GitHubProjectMiner.kt
  modules/mining-pipeline/github-project-miner/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/miner/github/MavenLibraryVersionVerifier.kt
Labels: code quality

#370 If a Statement is a Static Invoke, Check Method Reference Declaring Class
  modules/application/src/main/kotlin/org/cafejojo/schaapi/OptionSets.kt
  modules/mining-pipeline/jimple-library-usage-graph-generator/build.gradle
  modules/mining-pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/JimpleLibraryUsageGraphGenerator.kt
  modules/mining-pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/processors/UserUsageProcessor.kt
  modules/mining-pipeline/jimple-library-usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/Helpers.kt
  modules/mining-pipeline/jimple-library-usage-graph-generator/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/processors/UserUsageProcessorTest.kt
  modules/mining-pipeline/jimple-pattern-filter/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/patternfilter/jimple/InsufficientLibraryUsageFilterRule.kt
  modules/mining-pipeline/jimple-pattern-filter/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/patternfilter/jimple/libraryusagefilters/BranchStatementFilter.kt
  modules/mining-pipeline/jimple-pattern-filter/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/patternfilter/jimple/libraryusagefilters/Filter.kt
  modules/mining-pipeline/jimple-pattern-filter/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/patternfilter/jimple/libraryusagefilters/RecursiveGotoFilter.kt
  modules/mining-pipeline/jimple-pattern-filter/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/patternfilter/jimple/libraryusagefilters/StatementFilter.kt
  modules/mining-pipeline/jimple-pattern-filter/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/patternfilter/jimple/libraryusagefilters/ValueFilter.kt
  modules/mining-pipeline/jimple-pattern-filter/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/patternfilter/jimple/InsufficientLibraryUsageFilterRuleTest.kt
  modules/mining-pipeline/jimple-pattern-filter/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/patternfilter/jimple/libraryusagefilters/Helpers.kt
  modules/mining-pipeline/jimple-pattern-filter/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/patternfilter/jimple/libraryusagefilters/RecursiveGotoFilterTest.kt
  modules/mining-pipeline/jimple-pattern-filter/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/patternfilter/jimple/libraryusagefilters/StatementFilterTest.kt
  modules/mining-pipeline/jimple-pattern-filter/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/patternfilter/jimple/libraryusagefilters/ValueFilterTest.kt
Labels: bug

#378 Catch exceptions while constructing URLs
  modules/mining-pipeline/github-project-miner/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/miner/github/GitHubProjectDownloader.kt
  modules/mining-pipeline/github-project-miner/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/miner/github/GitHubProjectDownloaderTest.kt
Labels: bug

#379 Improve feedback during the mining process
  modules/mining-pipeline/directory-project-miner/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/miner/directory/DirectoryProjectMiner.kt
  modules/mining-pipeline/github-project-miner/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/miner/github/GitHubProjectMiner.kt
  modules/mining-pipeline/github-project-miner/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/miner/github/SearchOptions.kt
  modules/mining-pipeline/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/MiningPipeline.kt
Labels: enhancement

#380 Fix #375
  modules/application/src/main/kotlin/org/cafejojo/schaapi/LazyRollingFileAppender.kt
  modules/application/src/main/resources/logback.xml
Labels: bug

#384 Skip compilation of tests
  modules/mining-pipeline/java-maven-project-compiler/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/projectcompiler/javamaven/JavaMavenProjectCompiler.kt
Labels: enhancement

#381 Resolve false-positive "empty jar" warning
  modules/mining-pipeline/java-jar-project-compiler/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/projectcompiler/javajar/JavaJarProjectCompiler.kt
Labels: bug

#382 Allow enabling debug output on command line
  README.md
  modules/application/build.gradle
  modules/application/src/main/resources/logback.xml
Labels: enhancement

#383 More debug logs
  modules/mining-pipeline/directory-project-miner/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/miner/directory/DirectoryProjectMiner.kt
  modules/mining-pipeline/github-project-miner/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/miner/github/GitHubProjectDownloader.kt
  modules/mining-pipeline/github-project-miner/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/miner/github/GitHubProjectMiner.kt
  modules/mining-pipeline/java-jar-project-compiler/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/projectcompiler/javajar/JavaJarProjectCompiler.kt
  modules/mining-pipeline/java-maven-project-compiler/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/projectcompiler/javamaven/JavaMavenProjectCompiler.kt
  modules/mining-pipeline/jimple-evosuite-test-generator/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/testgenerator/jimpleevosuite/TestGenerator.kt
  modules/mining-pipeline/jimple-library-usage-graph-generator/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/usagegraphgenerator/jimple/JimpleLibraryUsageGraphGenerator.kt
Labels: enhancement

#385 Don't 'compute' transitive dependencies in version verifier
  modules/mining-pipeline/github-project-miner/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/miner/github/MavenLibraryVersionVerifier.kt
Labels: enhancement

#386 Timed callable
  README.md
  modules/application/src/main/kotlin/org/cafejojo/schaapi/DirectoryMiningCommandLineInterface.kt
  modules/application/src/main/kotlin/org/cafejojo/schaapi/GitHubMiningCommandLineInterface.kt
  modules/application/src/main/kotlin/org/cafejojo/schaapi/OptionSets.kt
  modules/mining-pipeline/github-project-miner/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/miner/github/GitHubProjectMiner.kt
  modules/mining-pipeline/github-project-miner/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/miner/github/MavenLibraryVersionVerifier.kt
  modules/mining-pipeline/java-maven-project-compiler/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/projectcompiler/javamaven/JavaMavenProjectCompiler.kt
  modules/mining-pipeline/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/ProjectCompiler.kt
  modules/mining-pipeline/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/TimedCallable.kt
  modules/mining-pipeline/src/test/kotlin/org/cafejojo/schaapi/miningpipeline/TimedCallableTest.kt
Labels: enhancement

#387 Check for presence of pom.xml before packing
  modules/application/src/main/kotlin/org/cafejojo/schaapi/OptionSets.kt
  modules/mining-pipeline/github-project-miner/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/miner/github/GitHubProjectDownloader.kt
  modules/mining-pipeline/github-project-miner/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/miner/github/GitHubProjectMiner.kt
Labels: bug

#388 Catch encoding-related exceptions during unzipping
  modules/mining-pipeline/github-project-miner/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/miner/github/GitHubProjectDownloader.kt
Labels: bug

#389 General code quality
  modules/application/src/main/kotlin/org/cafejojo/schaapi/DirectoryMiningCommandLineInterface.kt
  modules/application/src/main/kotlin/org/cafejojo/schaapi/GitHubMiningCommandLineInterface.kt
  modules/application/src/main/kotlin/org/cafejojo/schaapi/MissingArgumentException.kt
  modules/application/src/main/kotlin/org/cafejojo/schaapi/OptionSets.kt
  modules/mining-pipeline/jimple-pattern-filter/src/main/kotlin/org/cafejojo/schaapi/miningpipeline/patternfilter/jimple/libraryusagefilters/BranchStatementFilter.kt
Labels: code quality
